### ISSUE TITLE
EfCoreValueConverter missing parameterless constructor

### ISSUE THREAD

**Issue by PoolPirate** [SteveDunn/Vogen#116]
### Describe the bug

In order for the value converter to work in the HaveConversion method a parameterless constructor is needed.
Currently trying to use the converter will throw 
```
System.InvalidOperationException: "Cannot create an instance of value converter type 'EfCoreValueConverter'. Ensure that the type can be instantiated and has a parameterless constructor, or use the overload of 'HasConversion' that accepts a delegate."
```

In contrast the StronglyTypedIds lib does provide a parameterless constructor in the source generated converter which does solve this issue.

### Steps to reproduce

1. Install latest version of EFCore (6.0.4) and Vogen (1.0.19)
2. In the DbContext override ConfigureConventions and configure a conversion with the source generated converter.
3. Create / Apply migrations will throw

### Expected behaviour

The value converter should come with a default parameterless constructor.

**Comment by PoolPirate** [comment]
I did look into making a PR but I really have no idea how to navigate this project 😅

**Comment by SteveDunn** [comment]
Many thanks for reporting @PoolPirate . I'll take a look. I can also see you've submitted a PR, so many thanks for that too! I'll take a look now.
