### ISSUE TITLE
Add support for Record and Record struct

### ISSUE THREAD

**Issue by MortenMeisler** [SteveDunn/Vogen#128]
### Describe the feature

Actually I just need the From and Validate method to be generated on a record struct and have all the features a record has (value equality, with, immuatable etc.)

**Comment by SteveDunn** [comment]
Thanks for the feedback. I'll look into that. Would you also want the code analysis errors (for `new`/`default` etc)?

**Comment by MortenMeisler** [comment]
> Thanks for the feedback. I'll look into that. Would you also want the code analysis errors (for `new`/`default` etc)?

Thank you.

Yep I think it's great you cannot use new to avoid mistakes and ensure validation. 

I guess (or hope) you don't need all the equality overrides as record already does it oob.

**Comment by SteveDunn** [comment]
Some notes on implementing this for record (classes):
* Removed the Vogen generated `ToString()`: the record `ToString` generates, e.g. `MyRecordClass { Value = 123 }`
* Vogen is designed for single items, so there's little value in `with`
* One of best features of records are primary constructors. This would break Vogens constraint of everything is created via the `From` method. But the analyzer could prohibit these uses
* The code generated by Vogen was pretty much identical to record anyway

**Comment by SteveDunn** [comment]
@MortenMeisler - this feature is now released in 1.0.21. Thanks again for the feedback. Please do let me know if there's any issues (hopefully there won't be!)

**Comment by MortenMeisler** [comment]
> @MortenMeisler - this feature is now released in 1.0.21. Thanks again for the feedback. Please do let me know if there's any issues (hopefully there won't be!)

Great, that was fast. Thanks!
