### ISSUE TITLE
Validation exception when deserializing an invalid value

### ISSUE THREAD

**Issue by SteveDunn** [SteveDunn/Vogen#171]
### Describe the bug

When deserializing, Vogen should not validate the data. The serializers should call the private constructor instead of the public `From` method (which _does_ validate).

Offending types are:
* `decimal`
* `float`
* `single`

### Steps to reproduce

Create a VO containing instance attributes with values that are not creatable publicly. Serialize it, then deserialize it. An exception should not be thrown, as no validation should occur.

### Expected behaviour

An exception should not be thrown, as no validation should occur.

**Comment by SteveDunn** [comment]
The reasoning behind wanting to evade validation during deserialization, is that VOs _can_ in fact be created with invalid value. Take, for instance, this:
```csharp
    [ValueObject]
    [Instance("Unspecified", 0)]
    [Instance("Invalid", -1)]
    public partial class VendorId
    {
        private static Validation Validate(int value) =>
            value > 0 ? Validation.Ok : Validation.Invalid("Must be greater than zero.");
    }
```
In our _domain_, it's entirely possible that a `VendorId` hasn't yet been specified. Or, it _has_ been specified, by, say, a user - but what they've supplied is either invalid or the vendor doesn't exist.

If we move these VOs, via serialization, to other processes, then we want to be able to get the original values back into the VO without it throwing exceptions.

Yes, this does allow people to 'cheat' and evade validation, but there's no way to 100% stop people from cheating. The intention of this library is to just make it harder to do the wrong thing.

It's also worth talking covering the whole topic of [de]serialization: ideally, domain ideas stay in the _domain_. It's often better to use primitives at the boundaries of your application. But to not provide the mechanism for people to pass VOs around would turn a lot a people off of using Vogen.

**Comment by SteveDunn** [comment]
A counter-argument against the point above is that user would expect validation exceptions to be thrown when they're given Value Objects over the wire, e.g. in an MVC controller.

MVC controllers will use the generated `TypeConverter`. These call the private constructor, which bypasses validation.

So, as well as the question "_should invalid values be allowed to be deserialzed into a Value Object?_", there is another question "_should the type converters have the same behaviour as the derserialization code?_"

**Comment by Blackclaws** [comment]
I've just run into this exact issue. I use ValueTypes in my aspnetcore configuration files and assumed that they would validate on type conversion, turns out that isn't the case. I think the solution with trying to check invalid values against the invalid instances could be a good solution. This should maybe be configurable so as not to break existing users depending on this behavior.

**Comment by SteveDunn** [comment]
Thanks for the comment @Blackclaws . I replied in the thread on the PR just now.

Great point on returning just the static instance for classes!

Thanks again!

**Comment by SteveDunn** [comment]
There will be a new parameter in config named `DeserializationStrictness`
`AllowAnything` - does no validation at all - anything is allowed in
`RunMyValidationMethod` - just runs user validation - if any
`CompareAgainstKnownInstances` - compares to any instances specified

The bottom two can be combined.

For the situation where instance values can change and we might be left data in the database that can never be deserialized, then we can use the existing `NormalizeInput` method, e.g.

```diff
[ValueObject(typeof(int), Conversions.DapperTypeHandler)]
[Instance(name: "Invalid", value: -1)]
public partial class Vo
{
+    private static int NormalizeInput(int input) => input <= 0 ? 1 : input;

    private static Validation validate(int value)
    {
        if (value > 0)
            return Validation.Ok;

        return Validation.Invalid("must be greater than zero");
    }
}
```

**Comment by Blackclaws** [comment]
I see a bug here already. It should be 
```
if(value == Unknown.Value)
  return Unknown;
```
you can also move the check against known instances before the actual call to new.

If they are flag enums I think its a better idea to have flags like:
```
Anything,
Validate,
KnownInstances
```
With the default being that both are set.

If validate is set, the validate code portion is generated. If KnownInstances is set the comparison to known instances is generated. Anything is just the fallback default value so you have an enum value that has all flags unset.

**Comment by SteveDunn** [comment]
Good point re. returning the instance rather than a new one.

Re. the flags, that's pretty much what we have:

```csharp
    /// <summary>
    /// Allows anything to be deserialized into your Value Object.
    /// </summary>
    AllowAnything = 0,

    /// <summary>
    /// If your Value Object has 'Instances', then those are considered valid during deserialization.
    /// </summary>
    AllowKnownInstances = 1 << 0,

    /// <summary>
    /// If your Value Object has a Validate method, it will be called to validate the incoming value during deserialization.
    /// </summary>
    RunMyValidationMethod = 1 << 1,

    /// <summary>
    /// If your Value Object has 'Instances', then those are considered valid during deserialization.
    /// If the incoming value doesn't match any known instance, and if your Value Object has a Validate method, it will
    /// be called to validate the incoming value during deserialization. 
    /// </summary>
    AllowValidAndKnownInstances = AllowKnownInstances | RunMyValidationMethod,

    Default = AllowValidAndKnownInstances,
```

**Comment by SteveDunn** [comment]
That latest NuGet package (2.0.2) has these changes. I'd be interested to see how it works for you.
