### ISSUE TITLE
Analyzer for prohibited new statements has false positives

### ISSUE THREAD

**Issue by Blackclaws** [SteveDunn/Vogen#182]
### Describe the bug

When calling functions that return ValueObjects and declaring arrays with elements that use target typed new, Vogen Analyzer prints a false positive for prohibited new.

My educated guess is that this is the culprit: https://github.com/SteveDunn/Vogen/blob/main/src/Vogen/Analyzers/CreationUsingImplicitNewAnalyzer.cs

### Steps to reproduce

Try this program with Vogen:
```
var normalObject = new Object[0];
// Expected Analyzer Error
var a = new GeneratedValueObject();
var b = Create(normalObject);
// Unexpected Analyzer Error
var c = Create(
    new Object[]
    {
       // This call is the issue
        new()
    });

GeneratedValueObject Create(Object[] normalObject)
{
    return GeneratedValueObject.From(10);
}

[ValueObject()]
partial class GeneratedValueObject
{
    
}
```

### Expected behaviour

No error on the function call with target typed new

**Comment by SteveDunn** [comment]
Thanks so much for the bug report - well found!

I'll prioritise this one as it's clearly not very good to have false compilation errors.

In the meantime, as a workaround, you can `ExtractVariable` on the creation of the parameter, e.g.

```csharp
            var objects = new Object[]
            {
                // This call is the issue
                new()
            };
            var c = Create(objects);

```

**Comment by Blackclaws** [comment]
An alternative solution is actually to just write:
```
var c = Create(
    new []
    {
       // This call is the issue
        new Object()
    });
```

Maybe that also helps you debug the source. I find source generators that I've written myself sometimes hard to wrap my head around so I didn't want to spend a couple of hours figuring out how that specific analyzer works when you are probably much more familiar :)

**Comment by SteveDunn** [comment]
@Blackclaws ,  the latest release should address your problem. Let me know if it doesn't. Thanks once again for your feedback
