### ISSUE TITLE
Annotate generated methods with [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]

### ISSUE THREAD

**Issue by Blackclaws** [SteveDunn/Vogen#185]
### Describe the feature

I'm currently running into the weird situation that my code coverage is tanking because it includes generated code by default. I could now exclude the whole type from code coverage, which is also probably what I'll do, but I think that just excluding all the internal methods that are in the generated code would be a nice to have.

**Comment by SteveDunn** [comment]
Thanks @Blackclaws - this will be in the next release - thanks again for your input!
