### ISSUE TITLE
IComparable<>

### ISSUE THREAD

**Issue by viceroypenguin** [SteveDunn/Vogen#201]
### Describe the feature

@SteveDunn Would you be opposed to an additional option that would automatically implement `IComparable<>`, in addition to `IEquatable<>`? There are cases where I would like to sort by the Id in order to do binary searches, etc. I understand not adding it to all objects, but it would be nice to be able to add it when desired.

**Comment by Herdo** [comment]
@viceroypenguin
Coming from the [strong type generator](https://github.com/Herdo/strongtypes/blob/master/src/DotNetStandard/StrongTypes/StrongTypeGenerator.tt) I wrote a few years ago using T4, I'm missing the functionality of **comparison** as well.

All underlying types do implement **`IComparable` and `IComparable<T>`**. Therefore, it should be easy to automatically generate the interface implementations for the value objects.

The linked T4 template generates these two methods (`types in code just as example`), allowing to use the value objects in many sorting / ordering / comparison operations:
```cs
/// <summary>
/// Compares the current instance with another object of the same type and returns
/// an integer that indicates whether the current instance precedes, follows, or
/// occurs in the same position in the sort order as the other object.
/// </summary>
/// <param name="obj">An object to compare with this instance.</param>
/// <exception cref="System.ArgumentException"><paramref name="obj"/> is not the same type as this instance.</exception>
/// <returns>
/// A value that indicates the relative order of the objects being compared. The
/// return value has these meanings: Value Meaning Less than zero This instance precedes
/// obj in the sort order. Zero This instance occurs in the same position in the
/// sort order as obj. Greater than zero This instance follows obj in the sort order.
/// </returns>
[ExcludeFromCodeCoverage]
int IComparable.CompareTo(object? obj)
{
    if (obj is InternalUserId other)
        return CompareTo(other);
    throw new ArgumentException($"{nameof(obj)} is not of the same type as this instance.", nameof(obj));
}

/// <summary>
/// Compares this instance to a specified <see cref="InternalUserId"/> and returns an indication of their relative values.
/// </summary>
/// <param name="other">A <see cref="InternalUserId"/> to compare to.</param>
/// <returns>A signed integer that indicates the relative order of this instance and <paramref name="other"/>.</returns>
[ExcludeFromCodeCoverage]
public int CompareTo(InternalUserId other)
{
    if (Equals(null, V))
        return 1;
    return V.CompareTo(other.V);
}
```

This would allow all value objects to be used in many sorting / ordering / comparison use cases.

**Comment by SteveDunn** [comment]
This sounds like a good idea. My initial thinking is that it should generate `IComparable` only if the underlying type is `IComparable`.
And I'm wondering if this should be opt-in, or opt-out for users. Or maybe neither and have it non-configurable and mandatory? 🤔 

What are your thoughts @viceroypenguin and @Herdo ?

**Comment by viceroypenguin** [comment]
I'm good with making it out-out or even non-configurable. I just didn't want to override any existing opinions on the matter when suggesting opt-in. Non-configurable based on the underlying type being `IComparable<>` would certainly be the easiest to implement. I can put something together this week for that fairly easily.

**Comment by Herdo** [comment]
I agree with @viceroypenguin .
If the underlying type implements `IComparable` or `IComparable<>` the valor object should implement them as well.

**Comment by SteveDunn** [comment]
> I'm good with making it out-out or even non-configurable. I just didn't want to override any existing opinions on the matter when suggesting opt-in. Non-configurable based on the underlying type being `IComparable<>` would certainly be the easiest to implement. I can put something together this week for that fairly easily.

@viceroypenguin - did you make any progress on this one this week? No worries if not, let me know if you'd like to hand it back if time doesn't permit.

**Comment by viceroypenguin** [comment]
Thanks for checking. Other projects came up and I didn't get as far as I'd hope. If you want to take it back, I'll let you. 🙂

**Comment by SteveDunn** [comment]
Have implemented `IComparable<T>` if T is `IComparable`.

And have added tests to confirm that VOs can be stored and sorted in collections.

I'm wondering if it's worth adding `operator <` if the underlying is `IComparable`... It seems like a natural thing to do, e.g. it would allow:

```chsharp
if(mySequentialId1 < mySequentialId2)
{
 ...
}
```

(and obviously `>` too)

**Comment by Herdo** [comment]
@SteveDunn This would work, too. I don't know about the performance impact, though (if `IComparable` implementation might be slower than `<` and `>` operators).

I took the long way by checking if the underlying type has the specific operators, and if they do, add them in the value object.
However, this always felt somewhat hacky because it relies on reflection and naming conventions.

But in general, yeah, it'd be good to have `<`, `>`, `<=` and `>=` as well.

**Comment by viceroypenguin** [comment]
I know I don't tend to think of directly comparing Ids. For me, the point is that they can be sorted by `.OrderBy()` or similar, so implementing `IComparable<>` is the relevant feature. 

That said, if it doesn't take too much work, adding operators would probably match expectations of an `IComparable<>`.

**Comment by SteveDunn** [comment]
I think I'll add the operator cloning as a different Issue. It doesn't look as easy as I thought, e.g. for `int`, I can't seem them declared (e.g. was expecting to see a `operator <(int other)`, but couldn't be see (but could see it for `decimal`, `double` etc.)

... and I suppose that it wouldn't harm to clone any other operator in the form of

`public static [underlying-type] operator [whatever]([underlying-type] input)

**Comment by viceroypenguin** [comment]
Thanks @SteveDunn!
