### ISSUE TITLE
Proposal: Implement TryParse

### ISSUE THREAD

**Issue by KennethHoff** [SteveDunn/Vogen#205]
### Describe the feature

<h2>Story time!</h2>
Over the last few days I've been trying to create an edge-to-edge Primitive Obsession-free [FastEndpoints](https://fast-endpoints.com)-based API using Vogen(duh..), and no matter what I did I got `Use of uninitialized Value Object at: <....>` when I got the request, even though the value was _clearly_ parseable into the type I wanted.

I then googled a few things and stumbled upon this article by the [Coding Militia](https://blog.codingmilitia.com/2022/01/03/getting-complex-type-as-simple-type-query-string-aspnet-core-api-controller/). In retrospect, I now see that it literally stated `TryParse` in the first section, but I actually did not see that until now.

About 15 minute later, after trying out a few things, I finally got an error message that actually helped me:
```
No public static bool TryParse method found for[...]
```

I then found [this](https://stackoverflow.com/a/70260503) on StackOverflow telling me that you can't use Complex Types as Query parameters. That did not feel right with me, so I looked into it some more (read: 5 minutes), and then figured.. "Why don't I just try implementing the TryParse method and see if that works?", so I did.. And it did!

Here's what I made:

```csharp
[ValueObject(typeof(Guid))]
public readonly partial struct SoupId
{
	public static bool TryParse(string? value, out SoupId result)
	{
		if (Guid.TryParse(value, out var parsed))
		{
			result = From(parsed);
			return true;
		}

		result = From(Guid.Empty);
		return false;
	}
}
```
It's literally just calling the normal Guid.TryParse inside.

(For informational sense, these are my assembly options:
```csharp
[assembly: VogenDefaults(typeof(int), Conversions.TypeConverter | Conversions.SystemTextJson | Conversions.EfCoreValueConverter)]
```

<h2>Proposal:</h2>

Implement the `TryParse` method for the ValueObjects to allow them to be used as Query string parameters.

**Comment by SteveDunn** [comment]
Hi @KennethHoff - sorry for the slow response. I think this sounds like a great idea. I also like the idea of FastEndpoints!

I suppose for this feature, the source generator could inspect the underlying type, e.g. `Guid`, to see if that has a `TryParse`, and then generate one if it does.

I'll take a look at this shortly, but I'm pleased to see you've got a workaround by implementing it yourself.

**Comment by Herdo** [comment]
This should make use of the `NotNullWhen` attribute:
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analysis#conditional-post-conditions-notnullwhen-maybenullwhen-and-notnullifnotnull

> In a nullable enabled context, You can communicate that idiom using the NotNullWhen attribute. When you annotate parameters for nullable reference types, make message a string? and add an attribute:

```cs
bool TryGetMessage(string key, [NotNullWhen(true)] out string? message)
{
    if (_messageMap.ContainsKey(key))
        message = _messageMap[key];
    else
        message = null;
    return message is not null;
}
```

**Comment by KennethHoff** [comment]
Just to be clear for people unaware of what that would do. It gives information to you and the compiler that the _input argument_ is not null after the method returns true.

Using the TryParse mentioned in the original post:

```csharp
var idString = <some potentially null string>;
var isValid = SoupId.TryParse(idString, out var realId)
if (isValid)
{
    // idString in this scope is guaranteed to be parseable to a SoupId, but it is still the unparsed value. 
    // realId is the actual SoupId ValueObject
}
// We know nothing more about the nullability of idString, as the TryParse doesn't actually check for null
// even if the annotation implies it does.
// What it actually does is check if it's able to be parsed
// "Hello World" is not null, but it's not parseable as a Guid, so it would still be "null" in this context
```

I do not understand the purpose of this, as the `idString` variable you send in is still not an actual Id - it is still the same string.

**Comment by KennethHoff** [comment]
Just to be clear for people unaware of what that would do. It gives information to you and the compiler that the _input argument_ is not null after the method returns true.

Using the TryParse mentioned in the original post:

```csharp
var idString = <some potentially null, potentially invalid Guid string>;
var isValid = SoupId.TryParse(idString, out var realId)
if (isValid)
{
    // realId is guaranteed to be non-null (and by extension, a valid SoupId, as it has passed the `From` test)
}
// realId is guaranteed to be invalid
```

**Comment by SteveDunn** [comment]
Just about to implement this. So far, the code generator has been blissully unaware of nullability, so I'm hoping that it shouldn't be too difficult for the source generator to find out the nullability of what's currently being compiled.

**Comment by SteveDunn** [comment]
I've been referencing this blog post for a while now, which is very useful: https://cezarypiatek.github.io/post/methods-with-special-signature/?s=09

Explains other 'duck typing' in C#

**Comment by SteveDunn** [comment]
One difficulty with this is that **all** `TryParse` methods from the underlying primitive must be hoisted up. For instance, here's `Int32`:

![image](https://user-images.githubusercontent.com/263416/190998164-4ac9289b-4735-434f-bac0-c56c35eccac6.png)

I initially had this logic:

* does the underlying type have any `TryParse` methods?
* do any return a bool
* do any take a string or readonlyspan of char as the first parameter
* do any take the underlying type as the second parameter as an out parameter

**Comment by SteveDunn** [comment]
I suppose the new logic could be:

* does the underlying type have any `TryParse` methods?
* do any have a return type of bool
* do any have a **last parameter** of the underlying type

For all matching methods, copy the signature.

**Comment by SteveDunn** [comment]
Implemented the above logic. The source generated for an underlying type of `Int32` is:

```csharp
    /// <inheritdoc cref="int.TryParse(System.ReadOnlySpan{char}, System.Globalization.NumberStyles, System.IFormatProvider?, out int)"/>
    /// <summary>
    /// </summary>
    /// <returns>
    /// The value created via the <see cref="From"/> method.
    /// </returns>
    /// <exception cref="ValueObjectValidationException">Thrown when the value can be parsed, but is not valid.</exception>
    public static global::System.Boolean TryParse(System.ReadOnlySpan<char> s, System.Globalization.NumberStyles style, System.IFormatProvider? provider, out MyIntVo result) {
        if(System.Int32.TryParse(s, style, provider, out var r)) {
            result = From(r);
            return true;
        }

        result = default;
        return false;
    }

    /// <inheritdoc cref="int.TryParse(System.ReadOnlySpan{char}, out int)"/>
    /// <summary>
    /// </summary>
    /// <returns>
    /// The value created via the <see cref="From"/> method.
    /// </returns>
    /// <exception cref="ValueObjectValidationException">Thrown when the value can be parsed, but is not valid.</exception>
    public static global::System.Boolean TryParse(System.ReadOnlySpan<char> s, out MyIntVo result) {
        if(System.Int32.TryParse(s, out var r)) {
            result = From(r);
            return true;
        }

        result = default;
        return false;
    }

    /// <inheritdoc cref="int.TryParse(string?, System.Globalization.NumberStyles, System.IFormatProvider?, out int)"/>
    /// <summary>
    /// </summary>
    /// <returns>
    /// The value created via the <see cref="From"/> method.
    /// </returns>
    /// <exception cref="ValueObjectValidationException">Thrown when the value can be parsed, but is not valid.</exception>
    public static global::System.Boolean TryParse(string? s, System.Globalization.NumberStyles style, System.IFormatProvider? provider, out MyIntVo result) {
        if(System.Int32.TryParse(s, style, provider, out var r)) {
            result = From(r);
            return true;
        }

        result = default;
        return false;
    }

    /// <inheritdoc cref="int.TryParse(string?, out int)"/>
    /// <summary>
    /// </summary>
    /// <returns>
    /// The value created via the <see cref="From"/> method.
    /// </returns>
    /// <exception cref="ValueObjectValidationException">Thrown when the value can be parsed, but is not valid.</exception>
    public static global::System.Boolean TryParse(string? s, out MyIntVo result) {
        if(System.Int32.TryParse(s, out var r)) {
            result = From(r);
            return true;
        }

        result = default;
        return false;
    }

```
