### ISSUE TITLE
Consider Supporting "Type Safe Enum" Pattern

### ISSUE THREAD

**Issue by wekempf** [SteveDunn/Vogen#273]
### Describe the feature

A "Type Safe Enum" is basically a ValueObject with slightly different usage pattern. You'd want to assign public static properties using a private constructor and a From factory method would only produce values generated.

```csharp
[TypeSafeEnum]
public partial struct Meridiem
{
   public static Meridiem AM = new Meridiem("AM");
   public static Meridiem PM = new Meridiem("PM");
}

// ...

var meridiem = Meridiem.From("AM"); // OK
var meridiem = Meridiem.From("am"); // Failure
```

I realize this is not the focus of Vogen, but the generated code is so close between the two, that I think this might be a worthwhile addition.

**Comment by SteveDunn** [comment]
An interesting idea - thank you @wekempf ! This kinda fits in with another change I'm thinking about: https://github.com/SteveDunn/Vogen/issues/221

**Comment by SteveDunn** [comment]
Hi @wekempf - I'm now looking to create at a spin-off library more geared towards smart enums. If you have any ideas, I'd appreciate hearing them! https://github.com/SteveDunn/Intellenum/discussions 
Thanks in advance.
