### ISSUE TITLE
Run snapshot tests in parallel

### ISSUE THREAD

**Issue by SteveDunn** [SteveDunn/Vogen#284]
### Describe the feature

The tests take ages to run (> 40 minutes).

Make them run in parallel to speed up PRs and merges.

**Comment by jammehcow** [comment]
Since I've effectively doubled the snapshot tests in #322, I'd be happy to pick this up. Gotta clean up after yourself! :wastebasket:

**Comment by SteveDunn** [comment]
I don't think this is possible. But they run a *lot* faster in .NET 9, so it's not a massive problem.
