### ISSUE TITLE
[Question] 'Today' ValueObject? Is it possible? (Default Immutable values?)

### ISSUE THREAD

**Issue by jeffward01** [SteveDunn/Vogen#287]
Hello!

I would like to know if ValueObjects with a 'default' (pre-assigned) value type is possible.  Such as for example:

Ideally these can also be readonly / **immutable** types

````csharp

// Would be nice to have option of struct or record
[ValueObject<int>]
public partial struct MinimumAge{}

var minAge = new MinimumAge();

// should pass
Assert.Equal(18, minAge)
````

Or perhaps an easier example:

````csharp
[ValueObject<DateTime>]
public partial   record Today { }


var today = new Today();

// should pass
Assert.True(DateTime.Today, today)


````

I read the documentation, and tried some samples locally and could not figure out how to do the above ^^ actions. 

Is it possible?

**Comment by SteveDunn** [comment]
Hi @jeffward01 - currently, it's not possible. `new` and `default` are prohibited; the only way to create one is via the `From` method, or via a predefined 'instance:

```csharp
[ValueObject]
[Instance("MinimumAge", 18)]
public partial struct Age { }
```

You can then use: `Assert.Equal(Age.From(18), Age.MinimumAge)`. But that doesn't sound like what you want; what you want is a default value _if you don't provide a value_. But in Vogen, the biggest constraint it has is that it's very difficult for someone to **not** provide a value.

**Comment by jeffward01** [comment]
@SteveDunn Thanks for getting back to me -

>  it's very difficult for someone to not provide a value.

This is good to know, this was my second question.

----

For my first question - What I am also trying to ask (sorry for not mentioning it earlier) is implicit equality operators.

Something like this:

![image](https://user-images.githubusercontent.com/12589359/202576272-3313d083-208f-4e72-aded-b1864080a832.png)


It might implement some interface (internally within [Vogen](https://github.com/SteveDunn/Vogen)) like this:

````csharp
public interface IOperators<in TSelf, in TOther, out TResult> 
where TSelf : IOperators<TSelf, TOther,TResult>

{
    static abstract TResult operator ==(TSelf self, TOther other);
    static abstract TResult operator ==(TOther self, TSelf other);
    static abstract TResult operator !=(TSelf  self, TOther other);
    static abstract TResult operator !=(TOther self, TSelf other);

}
````

The goal in my question is not really to protect against an empty value (but that is a **very important** thing to protect for). The goal is to compare an object such as `DateOnly` against a property like `someCustomer.Birthday`.

The customer can have a valueObject of `Birthdate` (this is simply a `DateOnly` value wrapped in a [Vogen](https://github.com/SteveDunn/Vogen) `ValueObject`.

````csharp
   public class Customer
    {
        public string FullName { get; set; }

       // 'Birthdate' is a Vogen ValueObject using 'DateOnly'
        public Birthdate DateOfBirth { get; set; }
        
    }
````
 
Then I can compare the `Birthdate` Vogen ValueObject to `DateOnly` as an example like this:

````csharp

        var someListOfCustomers = new List<Customer>();
        var today = DateOnly.FromDateTime(DateTime.Today);

        foreach (var someListOfCustomer in someListOfCustomers)
        {
            if (someListOfCustomer.DateOfBirth == today)
            {
                // Wish them a happy birthday
                // Process something....
            }
            else
            {
              // skip    
            }
        }
````

is it possible to compare Vogen ValueObjects to their implemented underlying type? Such as `int` and `Age` where `Age` is a vogen value type?

**Comment by SteveDunn** [comment]
> is it possible to compare Vogen ValueObjects to their implemented underlying type? Such as int and Age where Age is a vogen value type?

Yes, Vogen will always generate the `IEquable` code to compare the `Value` of the `ValueObject` to the primitive type it wraps, enabling things such as:

```csharp
            (Age.From(18) == 18).Should().BeTrue();
            (18 == Age.From(18)).Should().BeTrue();
```

> It might implement some interface (internally within [Vogen](https://github.com/SteveDunn/Vogen)) like this:

There's nothing like that, but it does implement, as above, `IEquatable`, and adds `Equals(ValueObject<DateOnly>)` and `Equals(DateOnly)`.

Also, if the underlying type is `IComparable`, then it generates the equivalent code to compare the `Value` of the Value Object to the primitive type that it wraps. Note that this only solves the problem of 'I need my Value Objects in a sortable collection'. It doesn't provide comparable operators `<` and `>`.

> For my first question - What I am also trying to ask (sorry for not mentioning it earlier) is implicit equality operators.

It sounds like everything you need is available. But on the subject of _implicit_ operators, some expect Value Objects to implement implicit **cast** operators. But these just cause confusion and weaken contracts. I documented that here: https://github.com/SteveDunn/Vogen/issues/14

Let me know if there's anything further I can help with to get what you want working.

**Comment by jeffward01** [comment]
Thanks for this! This helps a lot, I really appreciate your advice on this and the library! seriously some of the best in the C# community. really appreciate you. Thanks @SteveDunn
