### ISSUE TITLE
CA1036 ClassName should define operator(s) since it implements IComparable

### ISSUE THREAD

**Issue by jeffward01** [SteveDunn/Vogen#292]
### Describe the bug

Rider - EAP 2022.3 EAP 7

Not sure if this is a bug or not - but it seems that the 'Default' `ValueObject` generates a compiler warning of type `CA1036`.

I know that @SteveDunn and the community has spent alot of time building excellent analyzers, so I was not sure if this was a feature, bug, or something else.

See screenshot:
![image](https://user-images.githubusercontent.com/12589359/203678955-7b783e4f-9018-4102-b6f0-224fc15088ac.png)

### Steps to reproduce

1.) Generate a basic value object:

```csharp
[ValueObject<string>]
public readonly  partial  struct ClassName
{
    
}
```

2.) Build

3.) Compiler warning should appear

### Expected behaviour

I would expect that no compiler warning would appear as the generated code is 'expected' to conform to standard 'non-warning' inducing terms.

My understanding of the above statement may be incorrect.

---------

Related Issue(s):

https://github.com/SteveDunn/Vogen/issues/201

**Comment by jeffward01** [comment]
I just saw that this is a duplicate of: https://github.com/SteveDunn/Vogen/issues/241

Feel free to close this ticket please if its not helpful to have open.

Thanks

**Comment by jeffward01** [comment]
Perhaps add a feature to ignore warning's like this via the Analyzer? Not sure if that is possible to _ignore_ **or** something that would want to be done (might create issues by 'hiding' valuable warning data)

**Comment by jeffward01** [comment]
I just wanted to report this still persists: https://github.com/SteveDunn/Vogen/issues/241#issuecomment-1378044395 It appears that @glen-84 also experiences this.

I think this ticket (https://github.com/SteveDunn/Vogen/issues/292) and ticket (https://github.com/SteveDunn/Vogen/issues/241) are duplicated -- perhaps we can merge them? Not sure if GitHub has that feature

**Comment by SteveDunn** [comment]
Hi - sorry, I missed these comments. There's actually 3 aspects to this:

1. disable the CA warning which I think was the first fix that was added
2. _implement_ the non-generic `IComparable` - which was recently added (it literally just implements `int CompareTo(object other)`)
3. _implement_ any related operators if the underlying type has them (#241 )- which is yet to be done

Now that 1. and 2. are implemented and released, nobody should be seeing any CA errors as far as I know.

I intend to get around to 3.,
