### ISSUE TITLE
Instances of type bool does not compile

### ISSUE THREAD

**Issue by AthenaAzuraea** [SteveDunn/Vogen#297]
### Describe the bug

The following code:

`[ValueObject(typeof(bool))]
[Instance("Invalid", false)]
partial class Test2 { }`

Fails with a compile error "CS0103 The name 'False' does not exist in the current context".
The generated code looks like this:

`public static Test2 Invalid = new Test2(False);`

This looks like a bug to me. The source generator capitalizes the boolean value for some reason.
I have tested on VS 17.4 with both .NET6 and .NET7.

Incidentally, string literals and enums also generate the wrong code.
Is there any hope for a quick bug fix or a workaround? This is breaking the compile and I can't find a way to get around this issue.

### Steps to reproduce

Add the following code:

`[ValueObject(typeof(bool))]
[Instance("Invalid", false)]
partial class Test2 { }`

Compile.

### Expected behaviour

The code should compile.

**Comment by SteveDunn** [comment]
Many thanks for the bug report and apologies for the bug. This sounds similar to #283 .  I'll keep you updated.
