### ISSUE TITLE
Attributes derived from ValueObjectAttribute<T> don't generate source

### ISSUE THREAD

**Issue by jammehcow** [SteveDunn/Vogen#319]
### Describe the bug

When using a custom generic attribute derived from `ValueObjectAttribute<T>`, no source code is generated. This only happens in .NET 7 because of the usage of the C# 11 generic attributes language feature.

### Steps to reproduce

1. Create a .NET 7 console app and add the `Vogen` package (tested with `3.0.8`)
2. Create an attribute class that derives from `ValueObjectAttribute<T>`
```csharp
public class MyCustomVoAttribute<T> : ValueObjectAttribute<T> { }
```
3. Apply attribute to a VO struct
```csharp
[MyCustomVoAttribute<int>]
public partial struct SomeValueObject { }
```
4. Attempt to create a new instance of the VO from the main method
```csharp
var x = SomeValueObject.From(2);
Console.WriteLine(x.ToString());
```
5. Build the project

### Expected behaviour

The source generator should create a `*.g.cs` file containing the other part of the `SomeValueObject` struct. Instead, nothing is generated and the build fails due to `SomeValueObject.From` being missing.

**Comment by jammehcow** [comment]
I've done some basic debugging using the snapshot tests and found that the attribute filter's base type check is the culprit ([link](https://github.com/SteveDunn/Vogen/blob/7c750503cc75b0a5f84c4d87814d1e34892dc591/src/Vogen/VoFilter.cs#L26-L28)). It's expecting `Vogen.ValueObjectAttribute` but when deriving from that generic type, the base type's full name is `Vogen.ValueObjectAttribute<System.Int32>`.

If you can pick one of the following suggestions (or make another one) I'd be happy to PR this fix in:
 1. Add another condition to the base type name check: 
```csharp
attrs.Where(
    a => a.AttributeClass?.FullName() == "Vogen.ValueObjectAttribute"
        || a.AttributeClass?.BaseType?.FullName() == "Vogen.ValueObjectAttribute")
        || a.AttributeClass?.BaseType?.FullName().StartsWith("Vogen.ValueObjectAttribute<");
```
 2. Add another condition to the base type check that check's the base type's `BaseType` as well 🤯
 3. Change the output of `SemanticHelper.FullName()` to strip the generic type from the given type so that `Vogen.ValueObjectAttribute<System.Int32>` returns as `Vogen.ValueObjectAttribute` (might be worth renaming that method in that case)

**Comment by SteveDunn** [comment]
Thanks for the feedback @jammehcow !  I think option 2 is the best bet. It seems reasonable to restrict the level of hierercharcy to two layers, so just:

```csharp
        return attrs.Where(
            a => a.AttributeClass?.FullName() == "Vogen.ValueObjectAttribute"
                || a.AttributeClass?.BaseType?.FullName() == "Vogen.ValueObjectAttribute"
                || a.AttributeClass?.BaseType?.BaseType?.FullName() == "Vogen.ValueObjectAttribute");
```

**Comment by jammehcow** [comment]
Awesome, I'll get a fix in today 🎉
