### ISSUE TITLE
Implement non-generic counterpart for IComparable

### ISSUE THREAD

**Issue by glen-84** [SteveDunn/Vogen#323]
### Describe the feature

I'm seeing [RCS1241: Implement non-generic counterpart](https://github.com/JosefPihrt/Roslynator/blob/main/docs/analyzers/RCS1241.md).

> Publicly visible type that implements IComparable<T>, IComparer<T> or IEqualityComparer<T> should implement their non-generic counterpart.

**Comment by SteveDunn** [comment]
Thanks @glen-84 . Do you see this in any output from compiling with Vogen? I thought all analysers should ignore generated code.

**Comment by SteveDunn** [comment]
I'm currently implementing this. Before, it had `IComparable<T>`, and now it has just `IComparable`. The implementation is:
```csharp
 public int CompareTo(object other) {
            if(other == null) return 1;
            if(other is {primitive} x) return CompareTo(x);
            throw new global::System.ArgumentException(""Cannot compare to object as it is not of type {primitive}"", nameof(other));
        }"
```

I'm just wondering if it should follow the same pattern as `IEquatable<T>` and `IEquatable<[underlying]>`. They seem kinda different as one is for direct comparison, and 1 is for facilitating sorting (which is less strict).

**Comment by glen-84** [comment]
It's not coming from the generated code.

![image](https://user-images.githubusercontent.com/261509/215173001-8d7ee920-01c3-4b7c-ba6f-7d599b44aced.png)

(`Id` is just a subclass of the `ValueObject` attribute.)

**Comment by jeffward01** [comment]
I get this warning also - it even allows me to generate the code.  This is what it generates:

```csharp
[ValueObject] // <-- it occurs for all data-types, its not specific to 'numeric' or 'string'.
// ReSharper disable once PartialTypeWithSinglePart
public  partial struct ExampleDecimalValueObject
{
    public static bool operator <(ExampleDecimalValueObject left, ExampleDecimalValueObject right)
    {
        return left.CompareTo(right) < 0;
    }

    public static bool operator <=(ExampleDecimalValueObject left, ExampleDecimalValueObject right)
    {
        return left.CompareTo(right) <= 0;
    }

    public static bool operator >(ExampleDecimalValueObject left, ExampleDecimalValueObject right)
    {
        return left.CompareTo(right) > 0;
    }

    public static bool operator >=(ExampleDecimalValueObject left, ExampleDecimalValueObject right)
    {
        return left.CompareTo(right) >= 0;
    }
}
```

However, I see that Vogen also generates these operators:
```csharp
        public static global::System.Boolean operator ==(ExampleDecimalValueObject left, ExampleDecimalValueObject right) => Equals(left, right);
        public static global::System.Boolean operator !=(ExampleDecimalValueObject left, ExampleDecimalValueObject right) => !(left == right);

        public static global::System.Boolean operator ==(ExampleDecimalValueObject left, System.Decimal right) => Equals(left.Value, right);
        public static global::System.Boolean operator !=(ExampleDecimalValueObject left, System.Decimal right) => !Equals(left.Value, right);

        public static global::System.Boolean operator ==(System.Decimal left, ExampleDecimalValueObject right) => Equals(left, right.Value);
        public static global::System.Boolean operator !=(System.Decimal left, ExampleDecimalValueObject right) => !Equals(left, right.Value);
```

It is 'missing' the `<`, `<=`, `>`, `>=` operators.

I say 'missing', because it is difficult to say programmatically without knowing the Business use case if a string is greater than another string.  I guess you can do this with success for DateTime, and numerics, even perhaps for GUID.  But for strings, it might make less business sense.

I think the options are:

1.) add a pragma ignore, or investigate why the existing ignore is not working
2.) Implement it by default

**Comment by jeffward01** [comment]
![image](https://user-images.githubusercontent.com/12589359/215188812-35eb8016-eeb3-493e-a477-8c74d208b3b3.png)

![image](https://user-images.githubusercontent.com/12589359/215188986-835c480f-e015-452b-a082-1bd26391e42c.png)


Even at times (it is not reliable, as it randomly 'works' and randomly will not show the lightbulb.)  will show the yellow lightbulb and suggest to:

* Generate a validation method
* Generate the IComparable's like what was in my code snippet I pasted above

**Comment by halomademeapc** [comment]
wow I was just having an issue with sorting from this and came here to file an issue.  can't believe that it _just_ got fixed

thanks!
