### ISSUE TITLE
[Documentation Enhancement] --- `[Instance]` with `Guid` I have a solution that I did not see in the documentation

### ISSUE THREAD

**Issue by jeffward01** [SteveDunn/Vogen#325]
### Describe the feature

Hello all!

I saw in the [documentation here](https://github.com/SteveDunn/Vogen#can-i-represent-special-values) about this **SUPER** cool `Vogen` feature called `[Instance]` -- I particully like this feature alot, and I use it whenever I need 'skinny' [SmartEnum's](https://github.com/ardalis/SmartEnum).

I did not see a good way to generate an Instance using GUID, so I experimented and found a solution that we can add to the documentation if it is helpful. See below:

**Definition**
```csharp
[ValueObject<Guid>]
[Instance("Open", "Guid.Parse(\"f0238039-033a-4f87-998c-99965f433a70\")")]
// ReSharper disable once PartialTypeWithSinglePart
public readonly partial struct WaitListStatus {}
```

**Behind the scenes generation**
```csharp
// instance...

public static readonly WaitListStatus Open = new WaitListStatus(Guid.Parse("f0238039-033a-4f87-998c-99965f433a70"));
```

**Unit Test**
```csharp
    [Fact]
    public void VogenInstanceShouldBeEqual()
    {
        Guid expected = Guid.Parse("f0238039-033a-4f87-998c-99965f433a70");
        Assert.Equal(expected, WaitListStatus.Open.Value);
    }
```

---

Pretty nifty!!

Again, big thanks to the creator, and dare I say, the lord and savior of Source Generated value objects? @SteveDunn

**Comment by SteveDunn** [comment]
@jeffward01 - I'm now looking to create at a spin-off library more geared towards smart enums. If you have any ideas, I'd appreciate hearing them! https://github.com/SteveDunn/Intellenum/discussions/11  Thanks in advance.

**Comment by SteveDunn** [comment]
General discussion items here: https://github.com/SteveDunn/Intellenum/discussions

**Comment by SteveDunn** [comment]
@jeffward01 - I've done an initial release of [Intellenum](https://www.nuget.org/packages/Intellenum/)

Here's [the github repo](https://github.com/SteveDunn/Intellenum).

Thanks for the idea for this new project. I'm not sure how it'll turn out as there's quite a few similar projects. They all take slightly different approaches, so I'll try to borrow the best bits from each! :)
