### ISSUE TITLE
`[Instance]`  extensions methods, `GetName`  and other useful methods... Make `[Instance]` behave more like `SmartEnum`

### ISSUE THREAD

**Issue by jeffward01** [SteveDunn/Vogen#330]
### Describe the feature

Hey all, 
 
**Intro**

*  There is a great library called [SmartEnum](https://github.com/ardalis/SmartEnum) which is basically a `class` that behaves like an `enum`, however - each '`enum`'in this case can have multiple properties, and other handy features.

* Another related library is called [FastEnum](https://github.com/xin9le/FastEnum) - basically this library adds extension methods and a 'helper class' to iterate over the classic `enum` object, get the `nameof(SomeEnumField)` and the value of the enum field.  
   * I don't like how you must call the static instance of `FastEnum.GetValues<MyEnum>();` in order to get the list of values, it would be nice to use an extension method. I believe the purpose of the `FastEnum.MyMethod` is due to the cacheing, just FYI

* In `Vogen`, the `[Instance]` feature is very similar to this. 

I think it would be helpful / useful to bring some of the features over from `FastEnum` or `SmartEnum` over to the `[Instance]` attribute of `Vogen`.  Some examples of some methods that could be implemented are:

Example code (the methods will refer to this):

```csharp
[ValueObject<Guid>]
[Instance("Open","Guid.Parse(\"2cd66300-4557-4c90-9836-c9e53f943035\")")]
[Instance("Closed","Guid.Parse(\"a474000a-898a-4805-b7ec-e1d8dcdb460c\")")]
// ReSharper disable once PartialTypeWithSinglePart
public readonly partial struct VogenInstanceType {  }
```

* Get Name
   * Example Use: `var myStatusName = VogenInstanceType.Open.GetName()`
   *  Should return '"Open"`
* GetNames
* GetValue
   * Returns a `Instance` matching the input value
* GetValues
   * Returns a all of the values of the Vogen Instance
****

**Proposed Extension Methods**

_Disclaimes:_

* I quickly wrote this code, it can be improved upon im 100% sure of it
* The name `FastVogen`, is just a mindless placeholder, and it in no way is _fast_ in the way that `FastEnum` is fast. `FastEnum` implements fancy caching, `FastVogen` currently does not.
* Im sure the extension methods names and parameters can be improved upon, this is just an example
* This is just an example code, I dont think its worthy of any PR by any means

**Improvemnts to be made on example code:**
* I hard coded `GUID` _yuck_, would be nice to use Reflection or similar for flexibility
   * Would be really nice to keep the number of generic parameters, and parameters at a minimum, I dont think adding `TValue` as a generic parameter is a good solution

* Change the class name of `FastVogen`, perhaps just absorb it entirely into the Vogen generated classes
* Refactor extension method, names and parameters
* Add more extension methods
* Make more elegant
* I really don't like my use of `FastVogen.MethodName`, imo should be an extension method
* Comments, documentation, etc
* etc, etc, etc

Example code:

```csharp

public static class FastVogen
{
    public static string GetName<T>(string name)
        where T : struct
    {
        return GetNames<T>()
            .First(_ => _ == name);
    }

    /// <summary>
    ///     Returns the value of the VogenInstance object which matches the <paramref name="name" />
    /// </summary>
    /// <param name="name"></param>
    /// <typeparam name="T"></typeparam>
    /// <returns></returns>
    public static Guid GetValue<T>(string name)
        where T : struct
    {
        T vogenInstance = GetFieldValue<T>(name);

        return GetVogenValueFromStruct(vogenInstance);
    }

    /// <summary>
    ///     Returns the `VogenInstance` object which contains a matching value of <paramref name="value" />
    /// </summary>
    /// <param name="value"></param>
    /// <typeparam name="T"></typeparam>
    /// <returns></returns>
    /// <exception cref="ArgumentException"></exception>
    public static T GetByValue<T>(Guid value)
        where T : struct
    {
        foreach (string name in GetNames<T>())
        {
            T item = GetFieldValue<T>(name);
            Guid vogenValue = GetVogenValueFromStruct(item);

            if (vogenValue.Equals(value))
            {
                return item;
            }
        }

        throw new ArgumentException($"Value '{value}' not found.");
    }

    private static Guid GetVogenValueFromStruct<T>(T item)
        where T : struct
    {
        // This can probably be cleaned up and made more efficient.
        // I'm not sure if this is useful code, but it's here for now.
        Guid vogenValue = typeof(T).GetProperty("Value")
            ?.GetValue(item) is Guid
            ? (Guid)(typeof(T).GetProperty("Value")
                ?.GetValue(item) ?? Guid.Empty)
            : default;

        return vogenValue;
    }

    public static IEnumerable<Guid> GetValues<TVogenType>()
        where TVogenType : struct
    {
        return GetNames<TVogenType>()
            .Select(GetValue<TVogenType>);
    }

    public static IEnumerable<string> GetNames<TVogenType>()
        where TVogenType : struct
    {
        Type targetType = typeof(TVogenType);

        // See Ticket https://github.com/SteveDunn/Vogen/issues/326 for implementation details
        // This is randomly here, this should be a private method that is invoked on each method, in order
       // to ensure / verify that TVogenType is indeed a type generated by Vogen, and not something else
        if (!targetType.IsVogenValueObject())
        {
            throw new InvalidDataException("The target type is not a Vogen value object");
        }

        foreach (FieldInfo prop in targetType.GetFields(
                     BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic))
        {
            yield return prop.Name;
        }
    }

    private static T GetFieldValue<T>(string fieldName)
        where T : struct
    {
        object instance = Activator.CreateInstance<T>();
        object? typeToCreate = typeof(T).GetField(fieldName)
            .GetValue(instance);

        // Probably should throw an exception rather than return this       
        return (T)typeToCreate!;

        // Probably should throw an exception rather than return this
        //return typeToCreate is T?  typeToCreate : default;
    }
}
```

Unit Tests:
```csharp

public class VogenStronglyTypedIdTests
{
    private readonly Guid _vogenInstanceClosedGuid = Guid.Parse("a474000a-898a-4805-b7ec-e1d8dcdb460c");
    private readonly Guid _vogenInstanceOpenGuid = Guid.Parse("2cd66300-4557-4c90-9836-c9e53f943035");

    [Fact]
    public void VogenInstanceGuidShouldMatchEnumType()
    {
        Assert.True(this._vogenInstanceClosedGuid.Equals(VogenInstanceType.Closed.Value));
        Assert.True(this._vogenInstanceOpenGuid.Equals(VogenInstanceType.Open.Value));
    }

    [Fact]
    public void ShouldFindVogenInstanceEnumByValue()
    {
        VogenInstanceType expected = VogenInstanceType.Open;

        VogenInstanceType result = FastVogen.GetByValue<VogenInstanceType>(this._vogenInstanceOpenGuid);

        Assert.Equal(expected.Value, result.Value);
    }

    [Fact]
    // Not tested yet, but should work
    public void ShouldReturnAllVogenValuesFromAnInstance()
    {
        Guid[] expected = { this._vogenInstanceOpenGuid, this._vogenInstanceClosedGuid };
        IEnumerable<Guid> results = FastVogen.GetValues<VogenInstanceType>();

        // ReSharper disable once PossibleMultipleEnumeration
        Assert.NotEmpty(results);

        // ReSharper disable once PossibleMultipleEnumeration
        Guid[] resultArray = results.ToArray();
        Assert.Equal(expected.Length, resultArray.Length);
        foreach (Guid expectedGuid in expected)
        {
            Assert.Contains(expectedGuid, resultArray);
        }
    }

    [Fact]
    public void ShouldListAllInstanceNamesFromVogenInstance()
    {
        Assert.Equal(
            2,
            FastVogen.GetNames<VogenInstanceType>()
                .Count());
        Assert.Contains("Open", FastVogen.GetNames<VogenInstanceType>());
        Assert.Contains("Closed", FastVogen.GetNames<VogenInstanceType>());
    }

    [Fact]
    public void ShouldGetTargetInstanceNameFromVogenInstance()
    {
        // Example without the extension method
        Assert.Equal("Open", nameof(VogenInstanceType.Open));

        // I don't like this implementation, I think this can be improved upon
        Assert.Equal("Open", FastVogen.GetName<VogenInstanceType>("Open"));
    }

    [Fact]
    public void ShouldGetTargetInstanceValueFromVogenInstance()
    {
        Assert.True(this._vogenInstanceOpenGuid.Equals(VogenInstanceType.Open.Value));

        // I added this extension method, because it has a related extension method with the name of `GetValues` which returns an array of each value (Open GUID and Closed GUID)
        // I don't really like this extension method, because natively, `VogenInstanceType.Open.Value` is the same thing, I just added this for sake of completeness.
        // It would be nice to shorten this, and not require the use of 'nameof'
        Guid result = FastVogen.GetValue<VogenInstanceType>("Open");
        Assert.True(VogenInstanceType.Open.Equals(result));
    }
}
```

Thanks all, 

I guess this is more of an open discussion on a feature set of enhancements, rather than a `feature enhancement` ticket

**Comment by SteveDunn** [comment]
Thanks very much for the details enhancement @jeffward01 !

This almost sounds like a new library and source generator that _uses_ Vogen (and the code that Vogen generates).

Something like:

```
[EnumerationOf<Guid>] // <= source generator
[Instance("Open","Guid.Parse(\"2cd66300-4557-4c90-9836-c9e53f943035\")")]
[Instance("Closed","Guid.Parse(\"a474000a-898a-4805-b7ec-e1d8dcdb460c\")")]
public readonly partial struct MyGuid { }
```

which would generate something like:
```
public readonly partial struct MyGuid 
{
    private Dictionary<string, Guid> _lookup = {
      { "Open", Open.Value },
      { "Closed", Closed.Value },
    }; 

    // generated code includes, aside from what Vogen generates for the instances...:
    public static readonly (string, Guid)[] NamesAndValues = new { ("Open", Open.Value), ("Closed", Closed.Value) };
    public static readonly string[] Names = new[] { "Open", Closed" } ;
    public static Guid this[string name] => _lookup[name];
}
```

... but then, how would we envisage usage of `From` to potentially create instances that _aren't_ specified as pre-defined `Instance`s?

It's an interesting idea - and potentially a great application for a source generator (potentially dependent on, or spun-off of) Vogen!

**Comment by jeffward01** [comment]
Thanks for this feedback!

Yea, when you present it that way, it looks like it does not meet the 'core' Vogen' target goal.  Agreed 100%.

Basically I saw the use of `[Instance("Open","Guid.Parse(\"2cd66300-4557-4c90-9836-c9e53f943035\")")]` in `Vogen`, and found myself writing extension methods to go backwards in attempts to return the `Open` value as a 'Name', (The funny effort's we'll go to in order to avoid writing `nameof(Open)` haha).

such as:

```csharp
// LookupProductTypeEnum would be the Vogen object in this example

public LookupProductTypeEnum GetBy(string name) {  }

public LookupProductTypeEnum GetBy(Guid id) {  }

```

Yea, I agree with you now that I think about the feature a little deeper.  The goal of Vogen (correct me if im wrong) is:

* Single-property ValueObjects that cannot ever be in a `bad` state.  

Basically that at its core, by introducing a second property of `.Name` in this case, it opens a whole can of worms that, your write, its like writing a second library ontop of `Vogen.Core` (the current `Vogen` library).

_(Not directly related to Vogen) Ultimately this feature add-on was somewhat related to a LookupTable mini-tool source generator I have been thinking about: https://github.com/SpatialFocus/EntityFrameworkCore.Extensions/issues/24#issuecomment-1378326250_ 

### Answer to question

> ... but then, how would we envisage usage of From to potentially create instances that aren't specified as pre-defined Instances?

Honestly, I imagine just taking the feature-set over from SmartEnum or any other similar Enum project and throwing something like `throw new InvalidDataException();` or `throw new EnumName/ValueNotFoundException();`

You are absolutely write, this makes more sense to be implemented as `Vogen.Enums`, or a name that sounds a bit more fun than that.

----
### Closing

Thanks for your feedback! I'll add this to my to-do list once I get a few projects completed and off of my plate!

Is there a list we can put this on? It would not be a good fit for `Roadmap` or `Backlog`, but maybe a list for `Future extrapolations of Vogen`?

If not, we can just keep it here and close the issue.

Thanks again!



---

#### Off-topic

Off-topic, relating to DDD or general dev:

* I remember you mentioned a few times about how you don't use `Vogen` in the Infra layer, and keep it in the `Domain` layer, I get that, EfCore is just barely sufficently ready for StronglyTypeId's and such... which means a very painful development experience.

for my own learning or whatnot, im really curious about the general pattern / style you use to develop DDD applications.  It would be cool to see at some point a sample DDD project about how you use Vogen personally.  I know you have a ton on your plate, and there are 100 other DDD examples, so please put this at mega-low priority, but I was just curious.

No need to reply to this query!

Thanks
Jeff

**Comment by SteveDunn** [comment]
Had a bit of spare time today so I've been thinking about this a bit more. The source generator approach to enums looks like a good fit. I'd imagine it to be a cross between SmartEnums and FastEnums.

I'll clone the repo and give and see what it looks like - thanks again for the ideas!

Re. usage of Value Objects: I use it at work, but here's a [page](https://github.com/SteveDunn/Vogen/network/dependents) of open source projects that use Vogen.

You might [find this](https://github.com/erikshafer/event-sourcing-ecommerce) one of particular interest re. DDD
> A pragmatic solution showing how to design and build an architecture in .NET using techniques like Event Sourcing, DDD, and CQRS.

I use Value Objects in my [Blazor version of PacMan](https://github.com/SteveDunn/PacManBlazor). It's used in a few places for types that represent things like points, percentages, and durations.

**Comment by SteveDunn** [comment]
I'm now looking to create at a spin-off library more geared towards smart enums. If you have any ideas, I'd appreciate hearing them! https://github.com/SteveDunn/Intellenum/discussions/ Thanks in advance.
