### ISSUE TITLE
[Bug?] File names to long when forking the code

### ISSUE THREAD

**Issue by jeffward01** [SteveDunn/Vogen#333]
### Describe the bug

Hello all,

I was forking the code when I got this error upon pull down:

![image](https://user-images.githubusercontent.com/12589359/212552615-41b154a9-c779-448c-8a2e-6f7232c5278f.png)

It is very likely this issue is unique to me, as I use Windows, and i have quite a nested folder structure.  

However, I have forked much code before, and have not experienced this long issues.

I know that if I clone and fork this in my `C:\\` as an example, it should be fine.  But, usually people don't do that.

Not sure if this is a bug, or something that is unique to my system due to my folder structure.  For reference, this is the path I tried to fork it in:

`C:\Dev\Aeonic\GitHub\General\ForkedCode`

Thanks all

### Steps to reproduce

1.) Use this folder structure:

`C:\Dev\Aeonic\GitHub\General\ForkedCode`

2.) Fork the code, or clone it

### Expected behaviour

No errors due to file length

**Comment by SteveDunn** [comment]
Thanks for reporting @jeffward01 . I'll need to hash those filenames; there were some other tests that I'd hashed the filenames for, but I thought I'd gotten away with these ones (it's better to have a meaningful name, however ugly they may be!)
