### ISSUE TITLE
Netwonsoft.Json serializer fails when deserializing into nullable ValueObjects

### ISSUE THREAD

**Issue by Blackclaws** [SteveDunn/Vogen#344]
### Describe the bug

When using the Newtonsoft.Json serializer with nullable Vogen ValueObjects it fails at deserializing the "null" value.

### Steps to reproduce

1. Make a new console app
2. Add Vogen and Newtonsoft.Json
3. Paste this in Program.cs
```
using Newtonsoft.Json;
using Vogen;

TestValueObject? nullableValueObject = null;

var serialized = JsonConvert.SerializeObject(nullableValueObject);
Console.WriteLine(serialized);

var deserialized = JsonConvert.DeserializeObject<TestValueObject?>(serialized);

[ValueObject<string>(Conversions.NewtonsoftJson)]
public partial class TestValueObject{}
```
4. Run

### Expected behaviour

Null is successfully deserialized into a null object. 

The simplest fix is to simply return null from the serializer in case the incoming string is null. And to change the JsonSerializer return type from object to object?

I'm not sure if that breaks behavior that people are relying on, but I think this is a bug and not intended behavior.

**Comment by Blackclaws** [comment]
Just as an added comment. System.Text.Json is not vulnerable to this as it apparently handles "null" by itself and doesn't even pass it on to the Vogen deserialization function.

**Comment by jeffward01** [comment]
Here is an example of the NewtonsoftJsonConverter generated by Vogen:
```csharp
class ProfileIdentifierNewtonsoftJsonConverter : Newtonsoft.Json.JsonConverter
{
    public override bool CanConvert(System.Type objectType)
    {
        return objectType == typeof(ProfileIdentifier);
    }

    public override void WriteJson(
        Newtonsoft.Json.JsonWriter writer,
        object value,
        Newtonsoft.Json.JsonSerializer serializer
    )
    {
        var id = (ProfileIdentifier)value;
        serializer.Serialize(writer, id.Value);
    }

    public override object ReadJson(
        Newtonsoft.Json.JsonReader reader,
        System.Type objectType,
        object existingValue,
        Newtonsoft.Json.JsonSerializer serializer
    )
    {
        var guid = serializer.Deserialize<System.Guid?>(reader);
        return guid.HasValue ? ProfileIdentifier.Deserialize(guid.Value) : null;
    }
}

```

Questions for you:

1.) What is the error you are recieving
2.) Is it related to the Vogen internal error `Use of uninitialized Value Object.`
3.) Do you have any examples of a JSON Serializer that works? (Can you create your own implementation of a Newtonsoft Json Converter that works, then share it here?)

If I have time later I can explore this, but I don't think i'll have time for several days. If you can provide a working example (Question 3)  that would be great

**Comment by jeffward01** [comment]
Best case, if you can share a small console app so we can reproduce quickly that would be great. If not, in a few days I might have some time to explore this (I hope so).

Thanks!

**Comment by Blackclaws** [comment]
> Best case, if you can share a small console app so we can reproduce quickly that would be great. If not, in a few days I might have some time to explore this (I hope so).
> 
> Thanks!

I shared the complete console app right there :) that's all the code you need to reproduce it. And indeed what happens is that the deserialization function fails when confronted with a null value that is passed right along from the Newtonsoft.Json converter. 

The error you get is the one from the Deserialize function:
```  
 private static TestValueObject Deserialize(System.String value)
        {
             if (value is null)
            {
                throw new global::Vogen.ValueObjectValidationException("Cannot create a value object with null.");
            }
            return new TestValueObject(value);
        }
```
By the way, this is the Deserializer  that is built for me:
```
       class TestValueObjectNewtonsoftJsonConverter : Newtonsoft.Json.JsonConverter
        {
            public override bool CanConvert(System.Type objectType)
            {
                return objectType == typeof(TestValueObject);
            }

            public override void WriteJson(Newtonsoft.Json.JsonWriter writer, object value, Newtonsoft.Json.JsonSerializer serializer)
            {
                var id = (TestValueObject)value;
                serializer.Serialize(writer, id.Value);
            }

            public override object ReadJson(Newtonsoft.Json.JsonReader reader, System.Type objectType, object existingValue, Newtonsoft.Json.JsonSerializer serializer)
            {
                return TestValueObject.Deserialize(serializer.Deserialize<global::System.String>(reader));
            }
        }
 ```
 
 The issue is that serializer.Deserialize is not tested for null before passing it along to the Deserialize function. This is a difference in behavior between ValueTypes and ReferenceTypes being used as arguments.
 
 It seems to me that in the case of a ValueType its first read from the serializer and checked whether HasValue is true, and in the case of a reference type it is passed right along to the deserialize function.
 
The fix is rather simple, don't treat reference types differently as the Deserialize function will throw anyway when passed null. So change the code for ReadJson for reference types to:
```
 public override object ReadJson(Newtonsoft.Json.JsonReader reader, System.Type objectType, object existingValue, Newtonsoft.Json.JsonSerializer serializer)
            {
                var value = serializer.Deserialize<global::System.String>(reader);
                return value is null ? null :  TestValueObject.Deserialize(value);
            }
```

**Comment by Blackclaws** [comment]
I'll create a pull request with the fix.
