### ISSUE TITLE
[Documentation - Wiki Permissions] Ability to edit the Wiki

### ISSUE THREAD

**Issue by jeffward01** [SteveDunn/Vogen#345]
### Describe the feature

Hello!

It's great that there is a Wiki! Thanks for that 🚀 

I was trying to add some snippets to it, but I do not have permissions to add snippets: https://github.com/SteveDunn/Vogen/issues/326#issuecomment-1383189223 

I think you can make an approval process where only some users can add snippets, or, I also think you can 'open it to the public', but they'll still be a required review process to accept changes.  Not 100% sure.

I just wanted to let you know that I tried to edit the Wiki and was not able to.

Thanks!

**Comment by jeffward01** [comment]
I am going to try and clone the repo, and submit a PR to edit the Wiki.  Usually there is a button on the GUI to do so, but I did not see it.  I saw that you reacted to my comment with a 👍  so your already aware of it.  I opened up this ticket a bit pre-maturely.

If im not able to edit the wiki via code and PR's, then I'll re-open the ticket again.

Thanks!

**Comment by SteveDunn** [comment]
Thanks @jeffward01 . I just changed the permissions on the Wiki according to this article: https://docs.github.com/en/communities/documenting-your-project-with-wikis/changing-access-permissions-for-wikis

I added you as a collaborator earlier this week, so not sure what's going on. Anyway, let's see how it goes with 'anyone' able to edit the wiki (if it get spammed, which I doubt, then I'll take another look)
