### ISSUE TITLE
Add a Data property to the thrown validation exception.

### ISSUE THREAD

**Issue by sirphilliptubell** [SteveDunn/Vogen#376]
### Describe the feature

Many logging frameworks work better when exception messages can be aggregated (meaning they aren't unique). Currently the only way to include the validated value in the exception is to include it in the message. eg: `Validation.Invalid($"Invalid ssn: {value}")`. Instead the value should be added to the Data property on the exception. This would allow logging frameworks to see the same exception message but still expose the value separately in specific logs. eg:
```
private static Validation Validate(string? value) {
    return Validation.Invalid("The SSN specified is not valid")
        .WithData("value", value)
        .WithData("notes", "expected 9 digits but found 8");
}
```

Pull Request #375

**Comment by SteveDunn** [comment]
Closed via #375
