### ISSUE TITLE
Using c# 11 style attribute eg: [ValueObject<string>] does not trigger some of the code analyzers

### ISSUE THREAD

**Issue by ThomasSkyldahl** [SteveDunn/Vogen#389]
### Describe the bug

Hi I have been testing out the library and it's looking very promissing so far
but I stumpled upon a bug when using C# 11 style generic attributes 
it seems like a lot the the build in analyzers do not trigger when using the C# 11 generic attribute:

### Steps to reproduce

try out this sample code in your IDE:

```
[ValueObject(typeof(string))]
public readonly partial struct OldSchoolProductNumber {}

[ValueObject<string>]
public readonly partial struct NewSchoolProductNumber {}

public class Examples
{
     public Examples() 
     {
         _ = new OldSchoolProductNumber(); // VOG010 error seen in editor
         _ = new NewSchoolProductNumber(); // no errror seen in editor
     }
}
```
The `OldSchoolProductNumber ` shows an error message.
The `NewSchoolProductNumber` does not show an error message

### Expected behaviour

I would expect the errors to be seen for both types of ValueObject attribute delerations

**Comment by ThomasSkyldahl** [comment]
I added a pull request with a fix for the issue see: #390

**Comment by ThomasSkyldahl** [comment]
@SteveDunn Thanks for the quick merge and the refactor :) closing this bug

**Comment by SteveDunn** [comment]
Thank you for your contribution! I just tag and pushed a new nuget version, so it should be ready soon.
