### ISSUE TITLE
Disallow defaulting in arrays

### ISSUE THREAD

**Issue by SteveDunn** [SteveDunn/Vogen#40]
e.g. `CustomerId[] ids = new CustomerIds[10];`

**Comment by dzmitry-lahoda** [comment]
these seems will have limited unsound form of analyzer

**Comment by SteveDunn** [comment]
> these seems will have limited unsound form of analyzer

I don't actually think this is possible from just an analyzer. It would be unfair to stop this, syntacticaly. At least there'll still be meaningful runtime exceptions when using uninitialized value types
