### ISSUE TITLE
ToString should not throw

### ISSUE THREAD

**Issue by CheloXL** [SteveDunn/Vogen#402]
### Describe the feature

Right now, `ToString()` calls internally `Value`, that, if the VO is not initialized, throws. My problem is that the .net framework is calling `ToString()` internally (for debugging purposes) and now I'm getting exceptions that should not be there.

I'm solving this by overriding the method, but I think that if the VO is not initialized, the `ToString` should simply returns `null`.

**Comment by SteveDunn** [comment]
Thanks for the report @CheloXL . `ToString`, in my opinion, is still a way for a consumer to access the value of the value object. Vogen generates debugger display attributes which the debugger should use. For instance:

```csharp
    [global::System.Diagnostics.DebuggerTypeProxyAttribute(typeof(DateTimeInstanceDebugView))]
    [global::System.Diagnostics.DebuggerDisplayAttribute("Underlying type: System.DateTime, Value = { _value }")]
    public readonly partial struct DateTimeInstance : global::System.IEquatable<DateTimeInstance>, global::System.IEquatable<System.DateTime> ,  global::System.IComparable<DateTimeInstance>, global::System.IComparable
```

The proxy looks like:

```csharp
        internal sealed class DateTimeInstanceDebugView
        {
            private readonly DateTimeInstance _t;

            DateTimeInstanceDebugView(DateTimeInstance t)
            {
                _t = t;
            }

            public global::System.Boolean IsInitialized => _t._isInitialized;
            public global::System.String UnderlyingType => "System.DateTime";
            public global::System.String Value => _t._isInitialized ? _t._value.ToString() : "[not initialized]" ;

            #if DEBUG
            public global::System.String CreatedWith => _t._stackTrace?.ToString() ?? "the From method";
            #endif

            public global::System.String Conversions => @"Default";
     }
```

As well as not throwing, it also displays the stack trace that lead to the uninitialized instance.

There is [an issue with Rider](https://github.com/SteveDunn/Vogen/issues/306) with these attributes, but it can be controlled via global config.

What IDE are you using? Does the exception interrupt debugging at all, or is it more a nuisance to see lots of exceptions?

**Comment by CheloXL** [comment]
Oh.. sorry if I was unclear. I'm not talking about any IDE, I'm talking about (for example) MS `ILogger`. If I enable the Debug or Trace levels on the framework, as you can expect, it start logging more information. Sometimes, the framework logs objects that have uninitialized values and that's where the error is thrown.

Those objects are valid at the point where they are being logged (I will update their values), but since I'm working with structs, the starting object has the default values on VOs.

I think that `ToString` should never thrown (even on invalid VOs). It's like you throw on the `GetHashCode` or `Equals`.

**Comment by SteveDunn** [comment]
I think you're right: `ToString` should not throw an exception. I was looking [at the guidelines](https://learn.microsoft.com/en-us/dotnet/api/system.object.tostring?view=net-8.0#notes-to-inheritors), and the two most interesting things are: 

> * Your [ToString()](https://learn.microsoft.com/en-us/dotnet/api/system.object.tostring?view=net-8.0#system-object-tostring) override should not return [Empty](https://learn.microsoft.com/en-us/dotnet/api/system.string.empty?view=net-8.0) or a null string.

> * Your [ToString()](https://learn.microsoft.com/en-us/dotnet/api/system.object.tostring?view=net-8.0#system-object-tostring) override should not throw an exception.

I think it's reasonable for Vogen to return something like `[UNINITIALIZED]` in this case. What do you think?

**Comment by CheloXL** [comment]
For me that would be perfect.
