### ISSUE TITLE
HasCode of a Struct seems not to be correct

### ISSUE THREAD

**Issue by Miljankg** [SteveDunn/Vogen#41]
Hi!

Thanks for the library, it is really great. When testing it today, I noticed something interesting. I have my own struct defined like this:

```
[ValueObject(typeof(int))]
public readonly partial struct TestValue
{
}
```
I was interested in the way you implemented your generators and noticed that the GetHashCode() implementation within `StructGeneratorForValueAndReferenceTypes.cs` looks like this:
```
public readonly override int GetHashCode() => System.Collections.Generic.EqualityComparer<{item.UnderlyingType}>.Default.GetHashCode();
```
Here, I noticed two issues:
1. Integer value seems not to be playing any role in the calculation of the HashCode. This seems incorrect. There is also a `System.Collections.Generic.EqualityComparer<{item.UnderlyingType}>.Default.GetHashCode(int obj);` method that I assume could be used here.
2. The Struct type seems also to be excluded from this. This _may_ be intentional from your side, but I am not sure.

This differs from what the generators for classes do, as those include both the "main" type, the underlying type, and the value.

In the next step, I wrote a couple of unit tests to write my expectations down, and the tests failed. The code for the tests can be found below. 

Is my concern justified here, or is this intentional? Thanks in advance.

The test code can be found below:
```
using Vogen;
using Xunit;

namespace Playground.Api.Tests.Unit;

public sealed class VogelStructGetHashCodeTest
{
    [Fact]
    public void GetHashCode_SameTypeSameValue_HashCodeMustBeDifferent()
    {
        // Arrange.
        var value1 = TestValue.From(1);
        var value2 = TestValue.From(1);

        // Act.
        var hashCode1 = value1.GetHashCode();
        var hashCode2 = value2.GetHashCode();

        // Assert.
        Assert.Equal(hashCode1, hashCode2);
    }

    [Fact]
    public void GetHashCode_SameTypeDifferentValue_HashCodeMustBeDifferent()
    {
        // Arrange.
        var value1 = TestValue.From(1);
        var value2 = TestValue.From(2);
        var value3 = TestValue.From(3);

        // Act.
        var hashCode1 = value1.GetHashCode();
        var hashCode2 = value2.GetHashCode();
        var hashCode3 = value3.GetHashCode();

        // Assert.
        Assert.NotEqual(hashCode1, hashCode2);
        Assert.NotEqual(hashCode1, hashCode3);
        Assert.NotEqual(hashCode2, hashCode3);
    }

    [Fact]
    public void GetHashCode_DifferentTypeDifferentValue_HashCodeMustBeDifferent()
    {
        // Arrange.
        var value1 = TestValue.From(1);
        var value2 = SomeValue.From(2);

        // Act.
        var hashCode1 = value1.GetHashCode();
        var hashCode2 = value2.GetHashCode();

        // Assert.
        Assert.NotEqual(hashCode1, hashCode2);
    }

    [Fact]
    public void GetHashCode_DifferentTypeSameValue_HashCodeMustBeDifferent()
    {
        // Arrange.
        var value1 = TestValue.From(1);
        var value2 = SomeValue.From(1);

        // Act.
        var hashCode1 = value1.GetHashCode();
        var hashCode2 = value2.GetHashCode();

        // Assert.
        Assert.NotEqual(hashCode1, hashCode2);
    }
}

[ValueObject(typeof(int))]
public readonly partial struct TestValue
{
}

[ValueObject(typeof(int))]
public readonly partial struct SomeValue
{
}
```

**Comment by SteveDunn** [comment]
Hi @Miljankg - thanks for spotting - and thanks for the tests!  I just released 1.0.15 with a fix for structs. I'll add some more unit tests to check for this.

You're correct that the logic differs between classes and structs. The struct doesn't take into account its type.  But I think it should do so that it's more in line with the class generator.

I'll add this into the next release.

Thanks again - much appreciated! 👍

**Comment by Miljankg** [comment]
Hi @SteveDunn, you are welcome, and thanks to You for fixing it.

Please note, I have mentioned two things in my original post:

1. Missing parameter for GetHashCode - this is now ok.
2. Type of the struct not included in HashCode calculation - I may have to point out here that I was driven by what I saw in the Class generator implementation. As the class is not sealed, having type within the GetHashCode may help reduce collisions with the instances of the classes deriving from the one marked as a ValueObject. However, for structs and _sealed_ classes this may not make sense or it would not be _necessary_.

**Comment by SteveDunn** [comment]
@Miljankg - hi again, just catching up on things. Re you point about the type not being included for `struct`: this is intentional; it's unlikely you'll want to compare two structs of different types (unless they're boxed). The generated code for `record struct` also doesn't include the type in `GetHashCode`.

Thanks again for the feedback - please let me know if you find anything else!
