### ISSUE TITLE
Rider issues. Vogen crashes source generators.

### ISSUE THREAD

**Issue by CheloXL** [SteveDunn/Vogen#418]
### Describe the bug

I'm using Rider to develop, and depending on the number of VOs I have in my project, the source generator breaks badly and my solution splits red everywhere. I already reported this to JetBrains, and now I can restart source generators from inside Rider.

Now... they also added a small log where you can see what causes source generation to fail, and with Vogen I'm getting the following: **Exception was of type 'ArgumentException' with message 'The hintName 'Blinkay.Control.Domain.Entities_ShapeId.g.cs' of the added source file must be unique within a generator. (Parameter 'hintName')'**

Not sure if Vogen is causing this. But maybe you can take a look since I believe you already worked with Rider. You need to install the latest EAP to have this feature enabled.

### Steps to reproduce

Open a solution with several VOs and start to mess around with the code.

### Expected behaviour

Source generator should not fail.

**Comment by kcadduk** [comment]
Yeah, this is a real PITA. Have to remove the Vogen dependency, then re-add it

@CheloXL  -  How do you restart the source generators?

**Comment by CheloXL** [comment]
@kcadduk You need to install the latest Rider EAP (as that feature was added recently). Then on the actions pallete, find "restart source generators". I assigned a hot key combo to that, since I have to restart them several times a day.

**Comment by SteveDunn** [comment]
Thanks @CheloXL - sorry, that's not good! Rider does seem to have particular issues with source generators. I've sent JetBrains the link to the Vogen source code as Rider has a lot of problems with the solution, presumably because there's thousands of generated objects in it.

Saying that, I haven't personally seen your particular issue in any of the solutions where I use Vogen.

There does appear to be hits when searching for the error, which is a relief! I'll take a look. But in the meantime, have you got any Value Objects with identical names?

**Comment by SteveDunn** [comment]
Also, have you got this set? I don't know if affects anything yet though...

![Uploading image.png…]()

**Comment by CheloXL** [comment]
No, all my VOs have unique names. You must install the latest EAP to see the error I reported above, as that's a new feature. And no, I don't have enabled that option. I tried enabling it in the past to see if that solves anything, but didn't changed anything...

The only thing I noted is that the more VOs I have in my solution, the easiest to fail code analysis (to the point it is unusable... That's where the new feature is handy > restart source generators).

**Comment by SteveDunn** [comment]
Thanks. Could you share your build command line if it's at all special? I'm seeing online that others have seen this when they have `-nodeReuse` specified (whatever that is!)

**Comment by CheloXL** [comment]
No special at all. Never heard of `nodeReuse`. Now I have to find it out...

**Comment by SteveDunn** [comment]
Thanks. I found this: https://github.com/dotnet/roslyn/discussions/60272

Seems like a common problem. Did you have any source generated files open in the editor? I'm thinking that maybe the editor someone locked the file and couldn't delete it or overwrite it.

**Comment by CheloXL** [comment]
No I don't have any source generated files open. But I suspect the same (locked files). Maybe Rider's wide solution analysis is locking files in background?

**Comment by SteveDunn** [comment]
Hopefully this is 'fixed' in https://github.com/SteveDunn/Vogen/releases/tag/3.0.17

It tries an additional 10 times if the first attempt fails. Each attempt prefixes the filename with the attempt number, e.g. `1MyVo.g.cs`

**Comment by SteveDunn** [comment]
@CheloXL - did you have a chance to try this version? Any issues so far? I'm on [another thread](https://github.com/dotnet/roslyn/discussions/60272) trying to see if there's a bug in Vogen that's causing this issue or if it's Roslyn (or the IDE)

**Comment by CheloXL** [comment]
Yes, I'm using right now. Now it fails less, but when fails, it fails with everything, including the kitchen sink. 

I don't know how source generators get registered, but it looks like Rider executes Vogen on each keystroke (that's why you get conflicting names, probably source generators start to run in parallel and one instance can't delete files opened by another instance). Now from time to time my CPU goes max for a while (and I can see it's Rider) and I see the solution wide analysis re-starting several times in seconds.

I'm also using [mapperly](https://github.com/riok/mapperly) and it doesn't cause issues, so maybe you can take a look at how the source generator is registered.

**Comment by glen-84** [comment]
@CheloXL Where is the log file?

**Comment by CheloXL** [comment]
@glen-84 The error appears as a source generator error, not sure if it's logged somewhere.
Here:
![image](https://github.com/SteveDunn/Vogen/assets/201414/7cb83dd1-98c0-4d1e-9385-7e12c7ca0276)
