### ISSUE TITLE
Allow to use fully qualified type "Vogen.Validation" as the return value

### ISSUE THREAD

**Issue by kamparR** [SteveDunn/Vogen#425]
### Describe the bug

When writing custom validation method to the value object only Validation type is allowed as the return type. Problem is when someone is already using Validation as part of the namespace
![image](https://github.com/SteveDunn/Vogen/assets/9059682/7067c5e8-abba-4e7d-886b-64d3a5e15d82)

### Steps to reproduce

`[ValueObject(typeof(string))]
public readonly partial struct DataGroupItemId
{
    private static Vogen.Validation Validate(string input) => string.IsNullOrEmpty(input)
        ? Vogen.Validation.Invalid($"{nameof(DataGroupItemId)} cannot be empty")
        : Vogen.Validation.Ok;
}`

### Expected behaviour

Using Vogen.Validation type should also be allowed

![image](https://github.com/SteveDunn/Vogen/assets/9059682/a45dbe8b-250e-477c-b38d-e3eb61586018)

**Comment by SteveDunn** [comment]
Oops! Thanks for the bug report - I'll fix that ASAP

**Comment by SteveDunn** [comment]
@kamparR - this should be fixed in version 3.0.18 which I've just pushed to NuGet (should be there shortly).

Thanks again for the report. Let me know if there's any other issues!
