### ISSUE TITLE
Generate array of known instances

### ISSUE THREAD

**Issue by erri120** [SteveDunn/Vogen#443]
### Describe the feature

When specifying multiple known instances of a value object, the source generator should generate a `public readonly T[] KnownInstances` field that contains all known instances.

This is great for scenarios where the value object is almost being used like an enumeration type and only known instances are used/allowed.

**Comment by SteveDunn** [comment]
Hi, I started a very similar project but is focused more on enumerations . https://github.com/SteveDunn/Intellenum

Very keen on feedback, so please let me know what you think.

**Comment by SteveDunn** [comment]
Hi @erri120 - does Intellenum suit your requirements? Your feature fits better with an enum focused library rather than a value-object focused library.
I'll close this for now, but if you think there's compelling reasons to have this, then please let me know.

**Comment by erri120** [comment]
Intellenum works perfect for this.
