### ISSUE TITLE
Use `ThrowHelper` for exceptions

### ISSUE THREAD

**Issue by SteveDunn** [SteveDunn/Vogen#45]

**Comment by SteveDunn** [comment]
I'm still looking at this one, although I haven't been able to find a suitable bit of code that I can benchmark (in benchmark.net) that demonstrates any speed increase.

**Comment by SteveDunn** [comment]
> I'm still looking at this one, although I haven't been able to find a suitable bit of code that I can benchmark (in benchmark.net) that demonstrates any speed increase.

Profiling this is quite tricky, although there are performance gains to be had, so this item should be implemented.

**Comment by Herdo** [comment]
@SteveDunn What's the purpose for this? Maintainability or performance?

**Comment by viceroypenguin** [comment]
Performance- using a helper method improves the rendered code from JIT. 

https://docs.microsoft.com/en-us/windows/communitytoolkit/developer-tools/throwhelper#technical-details

**Comment by Herdo** [comment]
@viceroypenguin 👍 The `ThrowHelper` methods from [`CommunityToolkit.Diagnostics`](https://github.com/CommunityToolkit/dotnet/tree/main/CommunityToolkit.Diagnostics) would only be used for the system exceptions then. Is that the only purpose, or should the [`ValueObjectValidationException`](https://github.com/SteveDunn/Vogen/blob/main/src/Vogen.SharedTypes/ValueObjectValidationException.cs) receive a wrapper method as well, to benefit from the performance benefits?

**Comment by viceroypenguin** [comment]
Yes, other exceptions should be wrapped separately with a similar helper class to benefit from similar performance optimizations. All exceptions receive these optimizations, not just this library or the system exceptions - it's just that the system ones are the ones that make sense to put into `CommunityToolkit.Diagnostics`. Whether @SteveDunn wants to add a dependency to `CommunityToolkit.Diagnostics` or copy the relevant exceptions independently for Vogen is up to him.

**Comment by SteveDunn** [comment]
Looking at this one at long last! I don't really want to take a dependency on anything, so I'm thinking of generating a type that has all of the methods required for the exceptions that are thrown with Vogen.
I'm just wondering if this is something that has been, or is being, implemented in .NET 9.

**Comment by viceroypenguin** [comment]
> Looking at this one at long last! I don't really want to take a dependency on anything, so I'm thinking of generating a type that has all of the methods required for the exceptions that are thrown with Vogen. I'm just wondering if this is something that has been, or is being, implemented in .NET 9.

For `Vogen`'s case, I'd recommend having an `internal static class` with the helper methods. `ThrowHelper` or similar. In this case, I agree with avoiding the dependency on `CommunityToolkit.Diagnostics`, and you'll have to create your own methods for the `Vogen` exceptions anyway. Just my 2c.

**Comment by SteveDunn** [comment]
Implemented in 5.0.2
