### ISSUE TITLE
Value types are managed types in debug mode

### ISSUE THREAD

**Issue by erri120** [SteveDunn/Vogen#497]
### Describe the bug

In debug mode, a `StackTrace _stackTrace` field gets added to the generated partial type. If the type is a value type, this will automatically make the type a managed type:

### Steps to reproduce

Create a value type:

```csharp
[ValueObject<Guid>]
public readonly partial struct MyId { }
```

Try to use the value type as an unmanaged type in debug mode:

```csharp
Span<MyId> ids = stackalloc MyId[2];
```

Compiler complains with [CS0208](https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0208):

```
Cannot take the address of, get the size of, or declare a pointer to a managed type ('MyId')
```

### Expected behaviour

Value types are used when performance is wanted, since they are usually unmanaged and can be stack allocated. There should be an option to remove the `StackTrace _stackTrace` field in debug mode. Ideally, this option should be on by default.

**Comment by SteveDunn** [comment]
Very interesting again! Thank you for the bug report. 
My initial thought is to add something to the configuration to enabled this to be omitted.
This, along with your other bug report about size, makes me think this should be an opt-in feature, as different sized types in debug and release could be problematic.
