### ISSUE TITLE
consider throwing System.ComponentModel.Annotations.ValidationException

### ISSUE THREAD

**Issue by dzmitry-lahoda** [SteveDunn/Vogen#50]
so it plays better with existing frameworks. at least aspnet

**Comment by SteveDunn** [comment]
A good point, and something that would be useful! I wonder if it'd still work if our exception was _derived from_ `System.ComponentModel.Annotations.ValidationException`.  I'll check

**Comment by dzmitry-lahoda** [comment]
Yes. It will work. In ASP.NET (and probably in UI like WPF) they handle such errors nice and derived.

**Comment by SteveDunn** [comment]
@dzmitry-lahoda - I'm just looking at this and have noticed that it'll require a dependency on `System.ComponentModel.DataAnnotations`. This would be the first dependency that Vogen takes, and I'd rather not have any dependencies.

I can see the benefit of it though, so perhaps we do need a global attribute that configures things like which exception to throw.

Could you explain what benefit this brings to aspnet? Is it auto `BadRequest` generation of input models, or something like that?

**Comment by SteveDunn** [comment]
Custom exceptions can now be specified globally (assembly) with `[VogenConfiguration(throws: typeof(YourException))]` - let me know if you have any issues.
