### ISSUE TITLE
ServiceStack.Text framework not supported

### ISSUE THREAD

**Issue by arteny** [SteveDunn/Vogen#548]
### Describe the feature

Pls add it's support for serialization.
Strings deserialized as null now.

**Comment by SteveDunn** [comment]
Hi - thanks for the feedback - I'll take a look at this when time permits.

**Comment by arteny** [comment]
> Hi - thanks for the feedback - I'll take a look at this when time permits.

Waiting too much for this. Now it is deserializing as "[UNINITIALIZED]" when it is a property of object

**Comment by arteny** [comment]
btw I found workaround adding this method to all of my ValueObject's:
`	public static MyValueObject Parse(string value) => From(value);`

**Comment by SteveDunn** [comment]
I'm glad you've found a workaround. Apologies for the delay in fixing this.

**Comment by SteveDunn** [comment]
Hi @arteny - could you check the latest version of Vogen? It should fix this issue as it now generates `Parse` itself

**Comment by SteveDunn** [comment]
@arteny - I just checked myself. It seems that primitive numers such as `int` etc. are support, however, `string` is not.
I think I need to generate a static constructor whose body is `JsConfig<Name>.DeSerializeFn = Name.From;`

**Comment by SteveDunn** [comment]
It looks like it calls any method that is `public static X Parse(string s)`. This works, by default, with types like `int` because they already have that method and it is hoisted up to the wrapper. 

I'll add another entry to the `Consersion` attribute to allow for ServiceStack.Text. When it is set, Vogen will generate the method above. Will hopefully have something shortly.

**Comment by SteveDunn** [comment]
This has now been implemented and will be in the next release.

**Comment by arteny** [comment]
Thanks, but this I found not fine for me. To make your conversion working, it is needed to add reference to ServiceStack.Text package for Domain project where VO is defined. But it is not good that this reference goes to other projects where it is not used (and convertion also not used).
So instead I still need add such code to make it working:
`public static MyValueObject Parse(string value) => From(value);`

**Comment by SteveDunn** [comment]
Hi @arteny  - I think there's a request to generate this in a separate project. I plan to get around to it when I have a bit of time.

**Comment by arteny** [comment]
> Hi [@arteny](https://github.com/arteny) - I think there's a request to generate this in a separate project. I plan to get around to it when I have a bit of time.

Yes, it will be an option to specify implement convertertion in other assembly than VO defined, it could solve my issue.
