### ISSUE TITLE
consider DebuggerTypeProxyAttribute to forward to internal type 

### ISSUE THREAD

**Issue by dzmitry-lahoda** [SteveDunn/Vogen#56]

**Comment by SteveDunn** [comment]
Great idea, thank you for this and the other issues @dzmitry-lahoda . I should be able to get around to them this week.

**Comment by SteveDunn** [comment]
@dzmitry-lahoda - would a `DebuggerDisplay` do the same thing? If not, could you tell me what you imagine the implementation to look like?

**Comment by dzmitry-lahoda** [comment]
Hi, yeah. Seems good.

I have seen .net structs which define ToString as type and Debugger Display as value afaik. So If DD("{Value}") than it may or may not show type or value provided. 

So 
```
[ValueObject(typeof(FooBar))]
[DebuggerTypeProxy(typeof(FooBarView))]
sruct FooBarView
{

    internal class FooBarView
    {
        [DebuggerBrowsable(DebuggerBrowsableState.RootHidden)]
        public FooBar Vaue
        {
            get
```
still can make sence. But I am unsure.

Imagine "MyType.Point" vs "(42.1, 34.2)"

**Comment by SteveDunn** [comment]
Done - thanks for the feedback!
