### ISSUE TITLE
Instance with 1 parameter

### ISSUE THREAD

**Issue by arteny** [SteveDunn/Vogen#562]
### Describe the feature

For the underlying type string, I often use a set of strings that need to be strongly typed. For example:
```
	[ValueObject(typeof(string))]
	[Instance("Users", "Users")]
	public struct TabName {}
```
means name and value are same, can you allow to add it specifying only one parameter for such cases like `[Instance("Users")]`?

**Comment by SteveDunn** [comment]
Hi @arteny - an interesting proposal. This looks like it might be better as an enum though. I spawned off '[Intellenum](https://github.com/SteveDunn/Intellenum)' due to the similarities between Vogen 'insances' and enums.

**Comment by arteny** [comment]
> Hi @arteny - an interesting proposal. This looks like it might be better as an enum though. I spawned off '[Intellenum](https://github.com/SteveDunn/Intellenum)' due to the similarities between Vogen 'insances' and enums.

ahh, ok, _Inetllenum_ looks good for this, then just a same purposal for it (to allow 1 parameter for string instances)

**Comment by SteveDunn** [comment]
@arteny - how are you getting on with Intellenum? I've closed this one, but let me know if you need any help.

**Comment by fbestfriends** [comment]
> @arteny - how are you getting on with Intellenum? I've closed this one, but let me know if you need any help.

Intellenum is good enough, but it miss same feature to create instances where value=name using 1 parameter. It looks more perfect and it is more misprint-resistance.

**Comment by SteveDunn** [comment]
@arteny @fbestfriends - I've created a feature request in Intellenum: https://github.com/SteveDunn/Intellenum/issues/127
