### ISSUE TITLE
Generated XML comments are malformed when using `ValueObject<int?>`

### ISSUE THREAD

**Issue by elianora** [SteveDunn/Vogen#568]
### Describe the bug

Using the following:

- Visual Studio 2022 Community 17.9.5
- dotnet 8.0.202

When attempting to use `ValueObject<int?>`, build a project. You will notice that [CS1570](https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs1570?f1url=%3FappId%3Droslyn%26k%3Dk(CS1570)) is triggered for malformed XML comments in the generated file.

### Steps to reproduce

1. Add the following to a new file in a project:
```csharp
[ValueObject<int?>]
public readonly partial struct MyType { }
```
2. Attempt to build the project
3. Notice that CS1570 is triggered in the generated file

### Expected behaviour

CS1570 is not triggered in the generated file and the XML comments are well-formed

**Comment by SteveDunn** [comment]
Hi @elianora  - thanks for the bug report. I can't seem to reproduce this issue. Have you got a solution that you can share?

**Comment by SteveDunn** [comment]
I'm closing this one for now, but if it's still an issue, please let me know.
Also, with regards to the nullable primitive: that (to my mind at least), it doesn't make sense to wrap a nullable primitive. Value objects represent values. In a way, it help to _stop_ the use of null (alongside types such as `Option`, `Maybe`, `OneOf` etc.
What scenario do you find this useful?
