### ISSUE TITLE
Improve performance and switch to `ForAttributeWithMetadataName`

### ISSUE THREAD

**Issue by SteveDunn** [SteveDunn/Vogen#574]
### Describe the feature

Follow the incremental generator best practices to improve performance. Also use `ForAttributeWithMetadataName` instead of checking attributes manually.

**Comment by Blackclaws** [comment]
This will most likely also solve: https://github.com/SteveDunn/Vogen/issues/575

**Comment by SteveDunn** [comment]
This is now implemented for finding assembly level config (`[VogenDefaults]`), but can't currently be used for `ValueObjectAttribute` as some people derive their own attributes from them, e.g. `public class IntVoAttribute : ValueObjectAttribute<int>`

In C# 12, this could be aliased with `using IntVo = Vogen.ValueObjectAttribute<int>;`

The plan is to create an analyser that spots when something is derived, and produces a warning.
