### ISSUE TITLE
[Cosmetic] 4.0.3 generates a warning in XML documentation

### ISSUE THREAD

**Issue by CheloXL** [SteveDunn/Vogen#588]
### Describe the bug

Trying to compile a project where I have set warnings as errors + generate documentation on build. It seems that the newly added method `TryFrom` has some errors in the XML documentation, as I'm getting the following:

```
0>DDS.Domain_ETag.g.cs(122,12): Warning CS1571 : XML comment has a duplicate param tag for 'value'
0>DDS.Domain_ETag.g.cs(128,11): Warning CS1573 : Parameter 'vo' has no matching param tag in the XML comment for 'ETag.TryFrom(string, out ETag)' (but other parameters do)
```

Peeking into the generated code I see where the error comes from:
![image](https://github.com/SteveDunn/Vogen/assets/201414/447e0fae-2f0d-4cf6-8d52-a63de9b8405f)
I believe the second param name should be **vo**.

### Steps to reproduce

Try to compile a project that has at least one VO, with the above settings set to true.

### Expected behaviour

No errors at compile time.

**Comment by Reonekot** [comment]
This hit me as well and it's borderline "Cosmetic" IMO - as you said, upgrading and having warnings as errors broke the build and took me some time to figure out the root cause. But Cosmetic in the sense that you can ignore ignore the warning in the project.
