### ISSUE TITLE
`InvalidCastException` in Vogen 4.0.3

### ISSUE THREAD

**Issue by viceroypenguin** [SteveDunn/Vogen#591]
### Describe the bug

When editing code in a project in VS 17.9.4, a CS8785 is generated in visual studio. This exception is not reported on the command line. 

![image](https://github.com/SteveDunn/Vogen/assets/1992555/cc03e2ac-0a29-4a4b-b06c-0a46bc3f1340)

### Steps to reproduce

In a blank project with Vogen 4.0.3 referenced, use the following code:
```cs
[assembly: VogenDefaults(conversions: Conversions.Default)]

Console.WriteLine("Test");

[ValueObject]
public readonly partial record struct TestId;
```

### Expected behaviour

There will be no compiler errors presented by Visual Studio.

**Comment by SteveDunn** [comment]
Thanks for the bug report. This duplicates #589 and will be fixed in v4.0.4
