### ISSUE TITLE
Analyzer to suggest using `readonly struct`

### ISSUE THREAD

**Issue by SteveDunn** [SteveDunn/Vogen#603]
It is preferable for users to use a `readonly struct` rather than just a `struct`. Implement an analyzer to suggest this, and possibly a codefix.

This was a result of the following thread.

              @SteveDunn A suggestion that came to my mind while reading this: maybe enhance the analyzers to promote the usage of `readonly struct` instead of a `struct` as an _Information_ or _Warning_ message?

_Originally posted by @Herdo in https://github.com/SteveDunn/Vogen/issues/52#issuecomment-1230748733_

**Comment by danigutsch** [comment]
Hi @SteveDunn . I wanted to take this issue, if that's alright

**Comment by SteveDunn** [comment]
That would be great, thank you!

**Comment by SteveDunn** [comment]
Hi, yes I think so. The benefits apply to them too. 👍
