### ISSUE TITLE
Stop R# reporting that VOs can be made static

### ISSUE THREAD

**Issue by SteveDunn** [SteveDunn/Vogen#607]
### Describe the feature

<img width="468" alt="image" src="https://github.com/SteveDunn/Vogen/assets/263416/a480eec4-4c0b-4048-a18d-de20261c95a6">

**Comment by DaBittna** [comment]
Just "driving by": I wanted to mention that `JetBrains.Annotations` has an attribute called [[MeansImplicitUse]](https://www.jetbrains.com/help/resharper/Reference__Code_Annotation_Attributes.html#MeansImplicitUseAttribute) that tells ReSharper / Rider that _another_ attribute (like `[ValueObject]`) has the same meaning as `[UsedImplicitly]`. With appropriate [flags](https://www.jetbrains.com/help/resharper/Reference__Code_Annotation_Attributes.html#ImplicitUseKindFlags) (maybe `ImplicitUseKindFlags.InstantiatedNoFixedConstructorSignature`), this should get rid of the warning / hint in the least intrusive way (fixing only this particular false-positive and leaving as many diagnostics enabled as possible).

**Comment by SteveDunn** [comment]
Thank you. Yes, I'm aware of that attribute but I don't really want Vogen
to take a dependency on JetBrains.Annotations. Those attributes are
fantastic though!
I suppose I could declare the attribute myself as internal.
But anyway, I just tried this again with the latest version of ReSharper in
a brand new project, and it doesn't report it.
Thanks again!

**Comment by SteveDunn** [comment]
Doesn't report this in the latest version of ReSharper
