### ISSUE TITLE
`fromPrimitiveCasting` and `toPrimitiveCasting` aren't consistent across `[ValueObject]` and `[VogenDefaults]`

### ISSUE THREAD

**Issue by aradalvand** [SteveDunn/Vogen#610]
### Describe the bug

This:
```cs
[ValueObject<Guid>(toPrimitiveCasting: CastOperator.Implicit)]
```
Generates this:
```cs
public static implicit operator System.Guid(GatewayId vo)
```
Whereas this:
```cs
[assembly: VogenDefaults(toPrimitiveCasting: CastOperator.Implicit)]
```
Generates this:
```cs
public static implicit operator GatewayId(System.Guid value)
```

It makes no sense. This is a bug.
`public static implicit operator GatewayId(System.Guid value)` represents a cast "to" the primitive, so what `[ValueObject]` does is the correct behavior here.

### Steps to reproduce

Outlined above.

### Expected behaviour

```cs
[assembly: VogenDefaults(toPrimitiveCasting: CastOperator.Implicit)]
```
should do what
```cs
[ValueObject<Guid>(toPrimitiveCasting: CastOperator.Implicit)]
```
does.

**Comment by SteveDunn** [comment]
Thanks for the bug report @aradalvand - well spotted. This has been fixed and will be available in the next release in a few hours.

**Comment by aradalvand** [comment]
@SteveDunn Thanks a lot for the quick fix!
(Hopefully 1K stars soon!)
