### ISSUE TITLE
Add option to opt out of primitive comparison

### ISSUE THREAD

**Issue by aradalvand** [SteveDunn/Vogen#611]
### Describe the feature
Hey there. Great library. Thanks for the efforts.

The behavior described in #561 is one that many of us would ideally like to avoid; as it seems to partly undermine the type-safety that value objects are all about in the first place (even if you find that arguable, there's still a reasonable argument to be made).

So, please introduce an option (e.g. `noPrimitiveComparison = true`) that allows those of us who want to prevent such comparisons at compile-time to opt out of this default behavior.

**Comment by SteveDunn** [comment]
Hi @aradalvand , thanks for the feedback. This makes perfect sense. I'll do this shortly.

**Comment by SteveDunn** [comment]
This will be in the next release
