### ISSUE TITLE
The JSON converter class shouldn't be `internal`

### ISSUE THREAD

**Issue by aradalvand** [SteveDunn/Vogen#613]
### Describe the bug

The nested `XSystemTextJsonConverter` class being `internal` causes JSON source generation to fail when the value object is in a different assembly; since the generated code wouldn't be able to reference it.

### Steps to reproduce

1. Clone https://github.com/aradalvand/vogen-test
2. `dotnet restore`
3. Open up `Program.cs` and look at the warning on `JsonContext`:
![image](https://github.com/SteveDunn/Vogen/assets/26527405/c0dd90c2-fc4f-45eb-8e72-d055ec14ec4d)
4. `dotnet run --project ./Two`
5. An exception is thrown too.

### Expected behaviour

This is likely caused by the fact that the nested converter class has an `internal` access modifier, and therefore the JSON source generator can't "see" it.

**Comment by SteveDunn** [comment]
Thanks for the report! This has now been changed and will be in the next release
