### ISSUE TITLE
CS0419 warning in `.g.cs` files when method overloading on auto generated functions

### ISSUE THREAD

**Issue by Ledmonds** [SteveDunn/Vogen#629]
### Describe the feature

Hey Team,

We are running into a _very small_ issue with the generated `.g.cs` files when method overloading on auto generated functions. 

Given the below example where one would like to use an additional `From()` method, in addition to that which is automatically generated. The compiled result contains a `CS0419` warning, as the `cref` now longer knows which `From` method is being referenced.

```
[ValueObject<string>(comparison: ComparisonGeneration.Omit)]
public readonly partial record struct ExampleId
{
    public static ExampleId NewId() => From(Guid.NewGuid().ToString());

    public static ExampleId From(Guid input) => From(input.ToString());

    private static Validation Validate(string input)
    {
        return !string.IsNullOrWhiteSpace(input)
            ? Validation.Ok
            : Validation.Invalid($"{nameof(ExampleId)} must not be null or whitespace");
    }
}
```

- The quick solution is to just rename the function to `FromGuid()`, however I find `From` very succinct, and it ultimately should be possible to method overload here.
- One could also make the `cref` for the auto-generated code typed, [as suggested here](https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0419).

Let me know what you think, I'm happy to open a PR if this gains some traction.

**Comment by SteveDunn** [comment]
Hi @Ledmonds - thanks for the feedback. I've [changed this to be specific to string](https://github.com/SteveDunn/Vogen/commit/3f38273d82a72e2b291ca61452331f560b4e0fe0#diff-ce7052a24aeac69203e69adb39381d8381b26884e49ffebfba45b4f02fb412e2). I also modified the comments for any `Parse` methods that might be hoisted from the users code. This will be in the next release.
Thanks again!

**Comment by jedmonds-tiplu** [comment]
@SteveDunn Awesome, thank you. Can you please drop the commit in this issue, I'd love to have a look at it.
