### ISSUE TITLE
OpenAPI schema should specify format UUID for Guids

### ISSUE THREAD

**Issue by Hona** [SteveDunn/Vogen#643]
### Describe the feature

I have the following:

```csharp
// Allow Strong IDs to generate nice OpenAPI schemas
[assembly: VogenDefaults(
    openApiSchemaCustomizations: OpenApiSchemaCustomizations.GenerateSwashbuckleMappingExtensionMethod
)]
```

Then this strong ID

```csharp
[ValueObject<Guid>]
public readonly partial record struct GameId;
```

This hints to a string, which is correct. However, we can add the format for a more accurate schema:

```
type: string
format: uuid
```

**Comment by SteveDunn** [comment]
Hi - thanks for your feedback. This has now been implemented and will be in the next release

Before:
<img width="279" alt="image" src="https://github.com/user-attachments/assets/79215d18-5c16-4039-b13c-bcad53009163">

After:
![image](https://github.com/user-attachments/assets/6e80e2b3-1501-4554-8915-d2fb82ae8b2a)

**Comment by Hona** [comment]
Sweet, thanks!
