### ISSUE TITLE
"Equals" and the comparison operators should be overridden when implementing "IComparable"

### ISSUE THREAD

**Issue by shupoval** [SteveDunn/Vogen#650]
### Describe the feature

SonarQube has a rule that ["Equals" and the comparison operators should be overridden when implementing "IComparable"](https://rules.sonarsource.com/csharp/RSPEC-1210/).

The following operator overloads are still missing in value objects generated by Vogen: <, <=, >, >=

It's a minor thing, but it would be great if Vogen could generate missing operator overloads too.

**Comment by SteveDunn** [comment]
Hi @shupoval - thanks for the feedback. There's is a [lengthy thread here](https://github.com/SteveDunn/Vogen/issues/241) about the same issue, so I'll close this one. In that thread you can see how to turn off `IComparable` if you don't need, thereby silencing SonarQube.
Thanks again!

**Comment by shupoval** [comment]
Oh, my mistake. I apologize for not checking the backlog for a similar issue.
Thanks a lot for pointing me in the right direction.
