### ISSUE TITLE
BSON serializer from higher-level project

### ISSUE THREAD

**Issue by aradalvand** [SteveDunn/Vogen#651]
### Describe the feature

Basically like #541 but for BSON serialization (support for which got added in #645).

Since the the MongoDB driver is an infrastructure-level tool just like EF, being able to create serializers/converters for it from a separate project makes just as much sense as it did for EF.

Thank you in advance.

**Comment by SteveDunn** [comment]
Thanks @aradalvand - I'll add that shortly. I had in the back of my mind that this would be needed at some point (I just didn't think it'd be soon!) :)

**Comment by alphaleonis** [comment]
I would love to see this for Json converters as well.

**Comment by SteveDunn** [comment]
Thanks for the feedback! Released in https://github.com/SteveDunn/Vogen/releases/tag/5.0.6-beta.1
