### ISSUE TITLE
Inaccurate explanation for why there are no to-primitive implicit operators by default

### ISSUE THREAD

**Issue by aradalvand** [SteveDunn/Vogen#660]
### Describe the bug

The README says:

![image](https://github.com/user-attachments/assets/6417dcec-3f77-4d85-b2b6-f84a335b6a17)

This is actually inaccurate. `age1 == osVersion` working is not a consequence of the to-primitive implicit operator alone, it's a consequence of **the combination** of that AND the primitive equality operators that Vogen generates by default — which you can now disable (#611), and this means that the following combination of options doesn't have the `age1 == osVersion` problem mentioned in the README:

```cs
[assembly: VogenDefaults(
    toPrimitiveCasting: CastOperator.Implicit,
    primitiveEqualityGeneration: PrimitiveEqualityGeneration.Omit
)]
```
![image](https://github.com/user-attachments/assets/6f07b553-6cf3-49b8-9848-846eb859b5d8)

### Steps to reproduce
-

### Expected behaviour
Up to you what should be done with this information :D
At least perhaps consider updating that bit of the README to actually communicate this fact. Thank you!

**Comment by SteveDunn** [comment]
Good point! Thanks for highlighting that! I shall update the documentation to reflect the fact that equality is driven by more than one thing.

**Comment by SteveDunn** [comment]
Thank you, I've updated the documentation in the FAQ page

**Comment by aradalvand** [comment]
This is perplexing to me, I feel like I'm losing my mind but it looks like I was wrong?!
If you try this code snippet right now:
```cs
using Vogen;

var foo = Foo.From("test");
var bar = Bar.From("test");
var result = foo == bar;
Console.WriteLine($"Equal? {result}");

[ValueObject<string>(
    toPrimitiveCasting: CastOperator.Implicit,
    primitiveEqualityGeneration: PrimitiveEqualityGeneration.Omit
)]
public readonly partial struct Foo;

[ValueObject<string>(
    toPrimitiveCasting: CastOperator.Implicit,
    primitiveEqualityGeneration: PrimitiveEqualityGeneration.Omit
)]
public readonly partial struct Bar;
```
It emits no errors on the `foo == bar` expression, even though `primitiveEqualityGeneration` is set to `Omit`. Wtf?!

I could swear it wasn't like this before...
