### ISSUE TITLE
Ability to "divide" source generation.

### ISSUE THREAD

**Issue by drusellers** [SteveDunn/Vogen#680]
### Describe the feature

I've been playing around with pushing some of the Vogen types into my "contracts" dlls for HTTP and Messaging contracts. These dll's are used internally to share the data between applications. I'd love to have a way to use the Vogen types in that project with the default JSON serialization support. But then in the consuming projects I could "register" those types for the EF Core generation.

In the "contracts" project

```csharp
[ValueObject<Guid>]
public partial struct UserId;
```

In the project that needs to store these types in the database, maybe steal an idea from AOT STJ

```csharp
[VogenGenerationOptions(...standard options)]
[ValueObject(typeof(UserId))]
internal partial class SourceGenerationContext : VogenContext
{
}
```

I'm not particular with the exact calls / syntax - just interested in discussing the option. 

Cheers

**Comment by SteveDunn** [comment]
Hi @drusellers . This is available for EFCore already: https://stevedunn.github.io/Vogen/efcoreintegrationhowto.html

Please let me know if the documentation successfully steers you towards your goal.
