### ISSUE TITLE
Support IXmlSerializable

### ISSUE THREAD

**Issue by wahtherewahhere** [SteveDunn/Vogen#690]
### Describe the feature

Can vogen support IXmlSerializable for xml serialization?
Thanks.

**Comment by SteveDunn** [comment]
That would be useful, thanks for the feedback @wahtherewahhere .

It looks like if this is implemented, it will only work for reference types: after a few hours of headscratching trying to figure out what why I was getting exceptions, I came across this:

https://github.com/dotnet/runtime/issues/99613

**Comment by SteveDunn** [comment]
In 5.0.5 beta 3
