### ISSUE TITLE
Swagger - MapVogenTypes: Enhancements

### ISSUE THREAD

**Issue by CheloXL** [SteveDunn/Vogen#693]
### Describe the feature

Hi,
There are a couple of enhancements that can be added to the existing generator, based on some research and custom code I'm using on my side.

Use `Type`, `Nullable` and `Format` when define an OpenApiSchema.

- `Type` should be "string" for strings, "integer" for ints (16/32). For any other number, "number" should be used. 
- `Nullable` should be set to false as usually you get the nullability from type annotations via `SupportNonNullableReferenceTypes` BUT when the VO is a struct, you also need to register the VO twice, one with the nullability set to false, and another with the nullability set to true, but after wrapping the VO into a Nullable<VO>. 
- `Format` should be "string" for strings, "int32" for int, "int64" for long, "float" for float and "double" for double.

Regarding `Nullable`: the following code is what I have in my library, as an example of what I'm saying, where `type` is the type of the VO (for example, "Street") and `vogenType` is the underlining type ("string").

```c#
var formatString = GetOpenApiTypeFormat(vogenType);
var typeString = GetOpenApiType(vogenType);
options.MapType(type, () => new() {Type = typeString, Nullable = false, Format = formatString});
if (!type.IsClass)
{
	var nullableType = typeof(Nullable<>).MakeGenericType(type);
	options.MapType(nullableType, () => new() {Type = typeString, Nullable = true, Format = formatString});
}
```

Hope I was clear, and thanks for all the work you have done with this library.

**Comment by SteveDunn** [comment]
Thanks for the feedback and suggestions @CheloXL ! I'll take a look at that when time permits, hopefully soon!

**Comment by SteveDunn** [comment]
Vogen currently maps the following C# types:
```csharp
        TypeAndFormat jsonType = primitiveType switch
        {
            "System.Int32" => new("integer"),
            "System.Single" => new("number"),
            "System.Decimal" =>new( "number"),
            "System.Double" => new("number"),
            "System.String" => new("string"),
            "System.Boolean" =>new( "boolean"),
            "System.Guid" =>new( "string", "uuid"),
            _ => new(TryMapComplexPrimitive(workItem))
        };
```
This matches the [Swagger docs](https://swagger.io/docs/specification/v3_0/data-models/data-types/#numbers). Those docs don't mention `int16`, but the [OpenAPI documentation ](https://spec.openapis.org/registry/format/int16) does, and says that `int16` should be `number`.

I just added added a branch for `Int64` (`long`), and filled out the formats:

```csharp
        TypeAndFormat jsonType = primitiveType switch
        {
            "System.Int32" => new("integer", "int32"),
            "System.Int64" => new("integer", "int64"),
            "System.Single" => new("number", ""),
            "System.Decimal" =>new( "number", "double"),
            "System.Double" => new("number", "double"),
            "System.String" => new("string", ""),
            "System.Boolean" =>new( "boolean", ""),
            "System.Guid" =>new( "string", "uuid"),
            _ => new(TryMapComplexPrimitive(workItem), "")
        };
```

`TypeAndFormat` is `record struct TypeAndFormat(string Type, string Format);`

Re. nulls, I've just added the functionality that re-registers value object that are value types (struct/record struct) as Nullable.
That'll be in the next beta release which I'll try to get out this morning. If you could take a look, that'd be great!

**Comment by SteveDunn** [comment]
In 5.0.5-beta3
