### ISSUE TITLE
List of accepted values

### ISSUE THREAD

**Issue by MatteoZampariniDev** [SteveDunn/Vogen#698]
### Describe the feature

Is it possible to add a source generated method/property that returns a collection of all defined [Instance] values? 

```Csharp
[ValueObject<string>] 
[Instance("Pdf", "pdf")]
[Instance("Txt", "txt")]
public readonly partial struct StoredFileType
{
    public static Validation Validate(string value) =>
        GetAllValues().Any(x => x.Value == value) ? Validation.Ok : Validation.Invalid("Invalid value");
    
    public static StoredFileType[] GetAllValues() => 
        [
            StoredFileType.Pdf, StoredFileType.Txt // source generation?
        ];
}
```
Thank you

**Comment by SteveDunn** [comment]
> ### Describe the feature
> 
> Is it possible to add a source generated method/property that returns a collection of all defined [Instance] values? 
> 
> ```Csharp
> [ValueObject<string>] 
> [Instance("Pdf", "pdf")]
> [Instance("Txt", "txt")]
> public readonly partial struct StoredFileType
> {
>     public static Validation Validate(string value) =>
>         GetAllValues().Any(x => x.Value == value) ? Validation.Ok : Validation.Invalid("Invalid value");
>     
>     public static StoredFileType[] GetAllValues() => 
>         [
>             StoredFileType.Pdf, StoredFileType.Txt // source generation?
>         ];
> }
> ```
> Thank you
> 

Hi, thanks for the feedback. Have a look at https://github.com/SteveDunn/Intellenum

**Comment by MatteoZampariniDev** [comment]
Thank you

**Comment by SteveDunn** [comment]
> Thank you

Very welcome, let me know if this suits your needs. Any feedback on Intellenum greatly appreciated too!
