### ISSUE TITLE
Having an uninitialized ValueObject inside a formatted string causes an endless loop by TryFormat

### ISSUE THREAD

**Issue by kimpenhaus** [SteveDunn/Vogen#710]
### Describe the bug

using Vogen 5.0.5

We have a value object inside a container object. That container object overrides ToString() and uses the value object inside a formatted string. When the value object is not initialized this causes a memory overflow because of the false flag returned from the TryFormat method - which leads to an endless loop inside the AppendFormatted:

--

<img width="3132" alt="image" src="https://github.com/user-attachments/assets/3f0fd0af-0ca2-416d-adec-aba90a832531">

--

<img width="1797" alt="image" src="https://github.com/user-attachments/assets/b549686d-7b14-494a-b659-890c22ca8004">

--

https://github.com/user-attachments/assets/6d39dd00-7892-4d15-be78-f0d4a1c28a3d

I have attached a sample below - the source itself is by far not good but reveals the problem.

### Steps to reproduce

```
// See https://aka.ms/new-console-template for more information

using Vogen;

var testContainer = new TestContainer();

Console.WriteLine(testContainer);

public class TestContainer
{
    public Test Test { get; set; }

    public override string ToString()
        => $"{Test}";
}

[ValueObject<Guid>]
public readonly partial struct Test;
```

### Expected behaviour

I would expect the string containing "[UNINITIALIZED]" as ToString would give.

**Comment by SteveDunn** [comment]
😬 nasty! Thanks for the report. I'll take a look at that later in the week when I'm back.

**Comment by kimpenhaus** [comment]
Thanks for your time @SteveDunn if there is anything I can assist you with please let me know

**Comment by kimpenhaus** [comment]
@SteveDunn thanks for fixing it such quickly - can confirm that it works well now - thanks!

**Comment by SteveDunn** [comment]
Great! Thanks for confirming.
