### ISSUE TITLE
Hanging / Extreme Memory usage on ValueObject.ToString with inner default value

### ISSUE THREAD

**Issue by thomhurst** [SteveDunn/Vogen#716]
### Describe the bug

Calling .ToString() on a ValueObject with an inner default/empty value hangs indefinitely and allocates memory continuously.

![image](https://github.com/user-attachments/assets/025020f5-6c3f-47df-9008-be83ab451fb0)

### Steps to reproduce

```
using Vogen;

AccountId.TryParse(null, out var id);
Console.WriteLine($"{id}");

[ValueObject<Guid>]
public readonly partial record struct AccountId;
```

### Expected behaviour

ToString() returns the default value of the underlying value type.

**Comment by thomhurst** [comment]
Ah yeah. It works fine on that beta version.

**Comment by SteveDunn** [comment]
Thanks for the feedback. Apologies. I'll get that released this weekend!
