### ISSUE TITLE
Vogen generates invalid namespace in SystemTextJsonConverterFactory_g.cs

### ISSUE THREAD

**Issue by Healios** [SteveDunn/Vogen#717]
### Describe the bug

It seems that when a namespace contains a hyphen ( - ), an invalid namespace is generated in the file SystemTextJsonConverterFactory_g.cs. The namespace "CRM_API" ends up being "CRM - API".

The namespace is however correct in the value-object's generated partial struct.

### Steps to reproduce

1. Download the following project https://github.com/Healios/vogen-namespace-error
2. Build it

### Expected behaviour

I was expecting the namespace to be "CRM_API".

**Comment by SteveDunn** [comment]
Thanks for bug report @Healios, and thanks for the repro! It's actually taking the assembly name, which _can_ have a hyphen, and using that without escaping it.
Doing a fix now.

**Comment by Healios** [comment]
Ah, got it 👍  Thank you so much for the prompt response @SteveDunn - really appreciate it!

**Comment by SteveDunn** [comment]
This is now in 6.0.0-beta.1. I've upped the major version as it includes a breaking change (albeit as small one), as a result of this fix.

The release notes are here: https://github.com/SteveDunn/Vogen/discussions/719

Thanks again for the feedback. Would welcome your thoughts in the discussion
