### ISSUE TITLE
Add support for "normalizing" ValueObjects

### ISSUE THREAD

**Issue by kirides** [SteveDunn/Vogen#80]
### Describe the feature

There are cases where `"   air " == " AIR      "` but with current code, the caller has to ensure that `Value.From(...)` is always called with `.ToUpperInvariant(), .Trim(), ...` or similar to ensure equality and proper `ToString` representation

Either a Flag, an Attribute or even "magically" understood method to provide the "normalized" Value would be great. Latter would allow us to do whatever we want with the value object on creation.

the generated code would then look somewhat like this

```cs
public static Value From(string value)
{
    value = Value.Normalize(value);
    Value instance = new Value(value);

    var validation = Value.Validate(value);
    if (validation != Vogen.Validation.Ok)
    {
        throw new Vogen.ValueObjectValidationException(validation.ErrorMessage);
    }


    return instance;
}
```

It would also allow for clamping of numeric values for example, where a "larger" value isn't technically a cause for an exception but allowed to be silently "fixed"

**Comment by SteveDunn** [comment]
Good idea! I had a similar concept in a previous implementation of this library; it was a delegate passed that did translation (and as I recall, it was exactly for this kind of this - to sanitize data)

**Comment by SteveDunn** [comment]
@kirides - a new version containing this feature was release today.
https://github.com/SteveDunn/Vogen/blob/main/samples/Vogen.Examples/TypicalScenarios/NormalizationExample.cs

Would be great to see if this is what you wanted.

**Comment by kirides** [comment]
works just like we need ;)
